### ISSUE TITLE
Failed to build on Ubuntu 16.04

### ISSUE THREAD

**Issue by bgdavidx** [neon-bindings/neon#198]
A neon app that is working perfectly on Ubuntu 14.04 is failing to build on Ubuntu 16.04

Error log:

```
> neon build

neon info running cargo
neon info cargo build --release
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading lazy_static v0.1.16
 Downloading neon v0.1.13
 Downloading bit-vec v0.4.3
 Downloading neon-runtime v0.1.13
 Downloading cslice v0.2.0
 Downloading gcc v0.3.44
   Compiling bit-vec v0.4.3
   Compiling gcc v0.3.44
   Compiling neon-runtime v0.1.13
error: failed to run custom build command for `neon-runtime v0.1.13`
process didn't exit successfully: `/home/ubuntu/server/node_modules/seat-bundler/native/target/release/build/neon-runtime-013ecc514adcef7f/build-script-build` (exit code: 101)
--- stdout
Skipping node-gyp installation as part of npm install.
/home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-runtime-0.1.13
├── bindings@1.2.1
├── nan@2.5.1
└─┬ node-gyp@3.5.0
  ├─┬ fstream@1.0.11
  │ └── inherits@2.0.3
  ├─┬ glob@7.1.1
  │ ├── fs.realpath@1.0.0
  │ ├─┬ inflight@1.0.6
  │ │ └── wrappy@1.0.2
  │ ├── once@1.4.0
  │ └── path-is-absolute@1.0.1
  ├── graceful-fs@4.1.11
  ├─┬ minimatch@3.0.3
  │ └─┬ brace-expansion@1.1.6
  │   ├── balanced-match@0.4.2
  │   └── concat-map@0.0.1
  ├─┬ mkdirp@0.5.1
  │ └── minimist@0.0.8
  ├─┬ nopt@3.0.6
  │ └── abbrev@1.1.0
  ├─┬ npmlog@4.0.2
  │ ├─┬ are-we-there-yet@1.1.2
  │ │ ├── delegates@1.0.0
  │ │ └─┬ readable-stream@2.2.5
  │ │   ├── buffer-shims@1.0.0
  │ │   ├── core-util-is@1.0.2
  │ │   ├── isarray@1.0.0
  │ │   ├── process-nextick-args@1.0.7
  │ │   ├── string_decoder@0.10.31
  │ │   └── util-deprecate@1.0.2
  │ ├── console-control-strings@1.1.0
  │ ├─┬ gauge@2.7.3
  │ │ ├── aproba@1.1.1
  │ │ ├── has-unicode@2.0.1
  │ │ ├── object-assign@4.1.1
  │ │ ├── signal-exit@3.0.2
  │ │ ├─┬ string-width@1.0.2
  │ │ │ ├── code-point-at@1.1.0
  │ │ │ └─┬ is-fullwidth-code-point@1.0.0
  │ │ │   └── number-is-nan@1.0.1
  │ │ ├─┬ strip-ansi@3.0.1
  │ │ │ └── ansi-regex@2.1.1
  │ │ └── wide-align@1.1.0
  │ └── set-blocking@2.0.0
  ├─┬ osenv@0.1.4
  │ ├── os-homedir@1.0.2
  │ └── os-tmpdir@1.0.2
  ├─┬ request@2.81.0
  │ ├── aws-sign2@0.6.0
  │ ├── aws4@1.6.0
  │ ├── caseless@0.12.0
  │ ├─┬ combined-stream@1.0.5
  │ │ └── delayed-stream@1.0.0
  │ ├── extend@3.0.0
  │ ├── forever-agent@0.6.1
  │ ├─┬ form-data@2.1.2
  │ │ └── asynckit@0.4.0
  │ ├─┬ har-validator@4.2.1
  │ │ ├─┬ ajv@4.11.5
  │ │ │ ├── co@4.6.0
  │ │ │ └─┬ json-stable-stringify@1.0.1
  │ │ │   └── jsonify@0.0.0
  │ │ └── har-schema@1.0.5
  │ ├─┬ hawk@3.1.3
  │ │ ├── boom@2.10.1
  │ │ ├── cryptiles@2.0.5
  │ │ ├── hoek@2.16.3
  │ │ └── sntp@1.0.9
  │ ├─┬ http-signature@1.1.1
  │ │ ├── assert-plus@0.2.0
  │ │ ├─┬ jsprim@1.4.0
  │ │ │ ├── assert-plus@1.0.0
  │ │ │ ├── extsprintf@1.0.2
  │ │ │ ├── json-schema@0.2.3
  │ │ │ └── verror@1.3.6
  │ │ └─┬ sshpk@1.11.0
  │ │   ├── asn1@0.2.3
  │ │   ├── assert-plus@1.0.0
  │ │   ├── bcrypt-pbkdf@1.0.1
  │ │   ├─┬ dashdash@1.14.1
  │ │   │ └── assert-plus@1.0.0
  │ │   ├── ecc-jsbn@0.1.1
  │ │   ├─┬ getpass@0.1.6
  │ │   │ └── assert-plus@1.0.0
  │ │   ├── jodid25519@1.0.2
  │ │   ├── jsbn@0.1.1
  │ │   └── tweetnacl@0.14.5
  │ ├── is-typedarray@1.0.0
  │ ├── isstream@0.1.2
  │ ├── json-stringify-safe@5.0.1
  │ ├─┬ mime-types@2.1.14
  │ │ └── mime-db@1.26.0
  │ ├── oauth-sign@0.8.2
  │ ├── performance-now@0.2.0
  │ ├── qs@6.4.0
  │ ├── safe-buffer@5.0.1
  │ ├── stringstream@0.0.5
  │ ├─┬ tough-cookie@2.3.2
  │ │ └── punycode@1.4.1
  │ ├── tunnel-agent@0.6.0
  │ └── uuid@3.0.1
  ├── rimraf@2.6.1
  ├── semver@5.3.0
  ├─┬ tar@2.2.1
  │ └── block-stream@0.0.9
  └─┬ which@1.2.12
    └── isexe@1.1.2


> @ build-release /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-runtime-0.1.13
> node-gyp build

TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
AR_x86_64-unknown-linux-gnu = None
AR_x86_64_unknown_linux_gnu = None
HOST_AR = None
AR = None
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
running: "ar" "crs" "/home/ubuntu/server/node_modules/seat-bundler/native/target/release/build/neon-runtime-26e6dd4052059e79/out/libneon.a" "build/Release/obj.target/neon/src/neon.o"
cargo:warning=ar: build/Release/obj.target/neon/src/neon.o: No such file or directory
ExitStatus(ExitStatus(256))


command did not execute successfully, got: exit code: 1



--- stderr
gyp ERR! build error
gyp ERR! stack Error: You must run `node-gyp configure` first!
gyp ERR! stack     at ReadFileContext.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:51:20)
gyp ERR! stack     at ReadFileContext.callback (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
gyp ERR! stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
gyp ERR! System Linux 4.4.0-64-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-runtime-0.1.13
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build-release"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! @ build-release: `node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build-release script 'node-gyp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-runtime-0.1.13/npm-debug.log
thread 'main' panicked at 'explicit panic', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.44/src/lib.rs:1140
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Cargo version:
```
> cargo -V
cargo 0.16.0-nightly (6e0c18c 2017-01-27)
```

Rustc version:
```
> rustc -V
rustc 1.15.1 (021bd294c 2017-02-08)
```

Neon version:
```
neon = "0.1.11"
```

Using Neon CLI ^0.1.7

Anyone have any idea?

**Comment by bgdavidx** [comment]
nevermind, this was a stupid mistake by me -- forgot to install Python. ignore!
