### ISSUE TITLE
Better handling of missing rustc executable

### ISSUE THREAD

**Issue by jugglingcats** [neon-bindings/neon#216]
Somehow on my build machine I lost rustc from my path, and neon build fails with the following error:

```
TypeError: Cannot read property 'toString' of null
    at Function.BuildSettings.current (/usr/local/lib/node_modules/neon-cli/dist/neon-cli/build-settings.js:29:13)
```

A minor issue but more helpful message would have prevented me from suspecting a node version problem (again!).

**Comment by kokokele** [comment]
me too。
------------------------
`neon-demo neon build
neon ERR! Cannot read property 'toString' of null

TypeError: Cannot read property 'toString' of null
    at Function.BuildSettings.current (/usr/local/lib/node_modules/neon-cli/dist/neon-cli/build-settings.js:29:13)
    at Project.<anonymous> (/usr/local/lib/node_modules/neon-cli/dist/neon-cli/project.js:59:61)
    at step (/usr/local/lib/node_modules/neon-cli/dist/neon-cli/project.js:32:23)
    at Object.next (/usr/local/lib/node_modules/neon-cli/dist/neon-cli/project.js:13:53)
    at /usr/local/lib/node_modules/neon-cli/dist/neon-cli/project.js:7:71
    at __awaiter (/usr/local/lib/node_modules/neon-cli/dist/neon-cli/project.js:3:12)
    at Project.build (/usr/local/lib/node_modules/neon-cli/dist/neon-cli/project.js:53:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/neon-cli/dist/neon-cli/ops/neon_build.js:46:50)
    at step (/usr/local/lib/node_modules/neon-cli/dist/neon-cli/ops/neon_build.js:32:23)
    at Object.next (/usr/local/lib/node_modules/neon-cli/dist/neon-cli/ops/neon_build.js:13:53)`
