### ISSUE TITLE
Failed to run custom build command for neon-runtime on Linux Fedora

### ISSUE THREAD

**Issue by weihanglo** [neon-bindings/neon#266]
Just start hello neon demo and the error occurred. 
I have tried Node.js version
- 6.11.5
- 8.0.0 
- 8.3.0 
- 8.8.0 

None of them can work. All versions got the same error. 

### Environment
- **Rust**: 1.22.0-nightly (4c053db23 2017-10-22)
- **Cargo**: 0.23.0-nightly (e447ac7e9 2017-09-27)
- **OS**: 4.13.5-200.fc26.x86_64 (Fedora 26)
- **Node.js**: v8.6.0 (installed via NVM)
- **npm**:  v5.3.0
- **Python**: 2.7.13
- **GCC**: 7.2.1 20170915

----

### Error Log

```
error: failed to run custom build command for `neon-runtime v0.1.20`
process didn't exit successfully: `/home/weihanglo/wd/neon-test/native/target/release/build/neon-runtime-f5dbbed362fc260f/build-script-build` (exit code: 101)
--- stdout
Skipping node-gyp installation as part of npm install.
up to date in 3.369s

> @ build-release /home/weihanglo/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-runtime-0.1.20
> node-gyp build

make: Entering directory '/home/weihanglo/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-runtime-0.1.20/build'
  CXX(target) Release/obj.target/neon/src/neon.o
make: Leaving directory '/home/weihanglo/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-runtime-0.1.20/build'
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
AR_x86_64-unknown-linux-gnu = None
AR_x86_64_unknown_linux_gnu = None
HOST_AR = None
AR = None
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
running: "ar" "crs" "/home/weihanglo/wd/neon-test/native/target/release/build/neon-runtime-5d6f5f89cc8f72fe/out/libneon.a" "build/Release/obj.target/neon/src/neon.o"
cargo:warning=ar: build/Release/obj.target/neon/src/neon.o: No such file or directory
exit code: 1

--- stderr
make: g++: Command not found
make: *** [neon.target.mk:95: Release/obj.target/neon/src/neon.o] Error 127
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/weihanglo/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.13.5-200.fc26.x86_64
gyp ERR! command "/home/weihanglo/.nvm/versions/node/v8.6.0/bin/node" "/home/weihanglo/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /home/weihanglo/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-runtime-0.1.20
gyp ERR! node -v v8.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build-release: `node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/weihanglo/.npm/_logs/2017-10-25T23_27_09_735Z-debug.log
thread 'main' panicked at '

Internal error occurred: Command "ar" "crs" "/home/weihanglo/wd/neon-test/native/target/release/build/neon-runtime-5d6f5f89cc8f72fe/out/libneon.a" "build/Release/obj.target/neon/src/neon.o" with args "ar" did not execute successfully (status code exit code: 1).

', /home/weihanglo/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.54/src/lib.rs:1670:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/home/weihanglo/wd/neon-test/node_modules/neon-cli/dist/neon-cli/target.js:124:35)
    at step (/home/weihanglo/wd/neon-test/node_modules/neon-cli/dist/neon-cli/target.js:32:23)
    at Object.next (/home/weihanglo/wd/neon-test/node_modules/neon-cli/dist/neon-cli/target.js:13:53)
    at fulfilled (/home/weihanglo/wd/neon-test/node_modules/neon-cli/dist/neon-cli/target.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN neon-test@0.1.0 No description
npm WARN neon-test@0.1.0 No repository field.

added 108 packages in 86.481s
```

**Comment by weihanglo** [comment]
It works after restart the system. Closed.
