### ISSUE TITLE
Failed to run custom build command for neon-runtime on Windows 10

### ISSUE THREAD

**Issue by MegaBlackLabel** [neon-bindings/neon#285]
I'm getting an error on windows when I compile the skeleton neon program using neon build.

## Environment
- rustc 1.24.0-nightly (5a2465e2b 2017-12-06)
- cargo 0.25.0-nightly (930f9d949 2017-12-05)
- OS: Windows 10 64bit
- Node.js: v8.9.0
- npm: 4.0.5
- yarn: 1.3.2
- Python: 2.7.12
- toolchain: nightly-x86_64-pc-windows-msvc (default)

## Operational procedure
```
npm install --global --production windows-build-tools

npm install --global neon-cli

neon new threading-hint

yarn
```

## Error Message
```
PS C:\0-work\rust\threading-hint> yarn
yarn install v1.3.2
[1/4] Resolving packages...
success Already up-to-date.
$ neon build
neon info forcing rebuild for new build settings
neon info running cargo
   Compiling cslice v0.2.0
   Compiling semver-parser v0.7.0
   Compiling neon-runtime v0.1.22
   Compiling semver v0.9.0
error: failed to run custom build command for `neon-runtime v0.1.22`
process didn't exit successfully: `C:\0-work\rust\threading-hint\native\target\release\build\neon-runtime-2657997b7d2e6c7e\build-script-build` (exit code: 101)
--- stderr
gyp ERR! build error
gyp ERR! stack Error: Could not find *.sln file. Did you run "configure"?
gyp ERR! stack     at C:\Program Files (x86)\Nodist\npmv\4.0.5\node_modules\node-gyp\lib\build.js:92:25
gyp ERR! stack     at f (C:\Program Files (x86)\Nodist\npmv\4.0.5\node_modules\once\once.js:25:25)gyp ERR! stack     at Glob.<anonymous> (C:\Program Files (x86)\Nodist\npmv\4.0.5\node_modules\glob\glob.js:151:7)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Glob.emit (events.js:211:7)
gyp ERR! stack     at Glob._finish (C:\Program Files (x86)\Nodist\npmv\4.0.5\node_modules\glob\glob.js:199:8)
gyp ERR! stack     at done (C:\Program Files (x86)\Nodist\npmv\4.0.5\node_modules\glob\glob.js:184:14)
gyp ERR! stack     at Glob._processReaddir2 (C:\Program Files (x86)\Nodist\npmv\4.0.5\node_modules\glob\glob.js:410:12)
gyp ERR! stack     at C:\Program Files (x86)\Nodist\npmv\4.0.5\node_modules\glob\glob.js:373:17
gyp ERR! stack     at RES (C:\Program Files (x86)\Nodist\npmv\4.0.5\node_modules\inflight\inflight.js:31:16)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files (x86)\\Nodist\\v-x64\\8.9.0\\node.exe" "C:\\Program Files (x86)\\Nodist\\npmv\\4.0.5\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd C:\Users\MY-NAME\.cargo\registry\src\github.com-1ecc6299db9ec823\neon-runtime-0.1.22gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files (x86)\\Nodist\\v-x64\\8.9.0\\node.exe" "C:\\Program Files (x86)\\Nodist\\npmv\\4.0.5\\bin\\npm-cli.js" "run" "build-release"
npm ERR! node v8.9.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! @ build-release: `node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build-release script 'node-gyp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\MY-NAME\.cargo\registry\src\github.com-1ecc6299db9ec823\neon-runtime-0.1.22\npm-debug.log
thread 'main' panicked at '

Internal error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\lib.exe" "/OUT:C:\\0-work\\rust\\threading-hint\\native\\target\\x86_64-pc-windows-msvc\\release\\build\\neon-runtime-6702b1b07bc0689d\\out\\libneon.a" "/nologo" "build\\Release\\obj\\neon\\neon.obj" with args "lib.exe" did not execute successfully (status code exit code: 1181).

', C:\Users\MY-NAME\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.54\src\lib.rs:1670:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (C:\0-work\rust\threading-hint\node_modules\neon-cli\lib\target.js:124:35)
    at step (C:\0-work\rust\threading-hint\node_modules\neon-cli\lib\target.js:32:23)
    at Object.next (C:\0-work\rust\threading-hint\node_modules\neon-cli\lib\target.js:13:53)
    at fulfilled (C:\0-work\rust\threading-hint\node_modules\neon-cli\lib\target.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
PS C:\0-work\rust\threading-hint>

```

How do I go about doing this trouble?

**Comment by dherman** [comment]
@tptee is going to see if he can repro on his Windows machine.

**Comment by heroes-coding** [comment]
+1

**Comment by tptee** [comment]
Hi @MegaBlackLabel ! I tried this out with the latest of MSVC 2017, Node 8, and Yarn and can't reproduce the error on either nightly or stable. I'm going to try to do the global installs like you did to see if `npm` is the culprit here!

**Comment by tptee** [comment]
Can't reproduce with `npm@4.0.5` either. Can you update MVSC and try again?

**Comment by MegaBlackLabel** [comment]
Hi @tptee
Just as you said, update to npm 5.6.0 and re-install global modules.
It's working as expected. Thanks for the advice!!!

**Comment by tptee** [comment]
Great! Let us know if you run into this again1

**Comment by AberrantWolf** [comment]
I am getting nearly the same kind of error. I just installed the latest NodeJS 8 and followed the guide, so I have:

- rustc 1.29.0-nightly (6a1c0637c 2018-07-23)
- cargo 1.29.0-nightly (506eea76e 2018-07-17)
- OS: Windows 10 64bit
- Node.js: v8.11.3
- npm: 5.6.0
- yarn: 1.9.4
- Python: 2.7.15
- toolchain: nightly-x86_64-pc-windows-msvc (default)

The error I have is very similar, but if you want me to make a new issue (since this one is old) please let me know.

```
PS C:\Users\scott\Documents\Programming\Hybrid\threading-hint> yarn
yarn install v1.9.4
[1/4] Resolving packages...
success Already up-to-date.
$ neon build
neon info forcing rebuild for new build settings
neon info running cargo
   Compiling semver-parser v0.7.0
   Compiling cslice v0.2.0
   Compiling neon-runtime v0.2.0
   Compiling semver v0.9.0
error: failed to run custom build command for `neon-runtime v0.2.0`
process didn't exit successfully: `C:\Users\scott\Documents\Programming\Hybrid\threading-hint\native\target\debug\build\neon-runtime-b5be163d18debf83\build-script-build` (exit code: 101)
--- stdout
'Skipping node-gyp installation as part of npm install.'
up to date in 0.538s
cargo:node_arch=x64
cargo:node_root_dir=C:\\Users\\scott\\.node-gyp\\8.11.3
cargo:node_lib_file=C:\\Users\\scott\\.node-gyp\\8.11.3\\<(target_arch)\\node.lib

> @ build-debug C:\Users\scott\.cargo\registry\src\github.com-1ecc6299db9ec823\neon-runtime-0.2.0
> node-gyp build --debug


C:\Users\scott\.cargo\registry\src\github.com-1ecc6299db9ec823\neon-runtime-0.2.0>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --debug )  else (node "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" build --debug )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\scott\.cargo\registry\src\github.com-1ecc6299db9ec823\neon-runtime-0.2.0\build\neon.vcxproj]


TARGET = Some("x86_64-pc-windows-msvc")
running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX64\\x64\\lib.exe" "/OUT:C:\\Users\\scott\\Documents\\Programming\\Hybrid\\threading-hint\\native\\target\\x86_64-pc-windows-msvc\\debug\\build\\neon-runtime-473e261f72bbfe3c\\out\\libneon.a" "/nologo" "build\\Debug\\obj\\neon\\neon.obj"
LINK : fatal error LNK1181: cannot open input file 'build\Debug\obj\neon\neon.obj'
exit code: 1181

--- stderr
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--debug"
gyp ERR! cwd C:\Users\scott\.cargo\registry\src\github.com-1ecc6299db9ec823\neon-runtime-0.2.0
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build-debug: `node-gyp build --debug`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build-debug script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\scott\AppData\Roaming\npm-cache\_logs\2018-08-10T13_39_54_003Z-debug.log
thread 'main' panicked at '

Internal error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX64\\x64\\lib.exe" "/OUT:C:\\Users\\scott\\Documents\\Programming\\Hybrid\\threading-hint\\native\\target\\x86_64-pc-windows-msvc\\debug\\build\\neon-runtime-473e261f72bbfe3c\\out\\libneon.a" "/nologo" "build\\Debug\\obj\\neon\\neon.obj" with args "lib.exe" did not execute successfully (status code exit code: 1181).

', C:\Users\scott\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.54\src\lib.rs:1670:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (C:\Users\scott\Documents\Programming\Hybrid\threading-hint\node_modules\neon-cli\lib\target.js:121:35)
    at step (C:\Users\scott\Documents\Programming\Hybrid\threading-hint\node_modules\neon-cli\lib\target.js:32:23)
    at Object.next (C:\Users\scott\Documents\Programming\Hybrid\threading-hint\node_modules\neon-cli\lib\target.js:13:53)
    at fulfilled (C:\Users\scott\Documents\Programming\Hybrid\threading-hint\node_modules\neon-cli\lib\target.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by kjvalencik** [comment]
@roderickmonk It's strange that you are having this same issue in linux. I'm able to build successfully in Ubuntu 16.04. Can you post the log?
