### ISSUE TITLE
Build error: node-gyp error on new project MacOS

### ISSUE THREAD

**Issue by Banashek** [neon-bindings/neon#298]
# Problem
Unable to build a new project created with `neon new`. (Looks similiar to [this comment](https://github.com/neon-bindings/neon/issues/222#issuecomment-323197368))
## Steps to reproduce
```
npm install --global neon-cli
neon new threading-hint
cd threading-hint
neon build
```

# Versions
MacOS: `10.13`
Nvm: `0.33.8`
Node: `9.5.0`
Neon: `0.1.22`
Cargo: `cargo 0.26.0-nightly (1d6dfea44 2018-01-26)`
Rustup: `1.10.0 (c6a8f7c60 2018-01-25)`
Rust: `nightly-x86_64-apple-darwin`

# Output
```
Error: failed to run custom build command for `neon-runtime v0.1.22`
process didn't exit successfully: `/Users/jon/code/Experiments/threading-hint/native/target/release/build/neon-runtime-0ab814686fc23fb5/build-script-build` (exit code: 101)
--- stdout
Skipping node-gyp installation as part of npm install.
up to date in 0.447s

> @ build-release /Users/jon/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-runtime-0.1.22
> node-gyp build

TARGET = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
AR_x86_64-apple-darwin = None
AR_x86_64_apple_darwin = None
HOST_AR = None
AR = None
TARGET = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
running: "ar" "crs" "/Users/jon/code/Experiments/threading-hint/native/target/release/build/neon-runtime-56ae8bb1d1629a4f/out/libneon.a" "build/Release/obj.target/neon/src/neon.o"
cargo:warning=ar: build/Release/obj.target/neon/src/neon.o: No such file or directory
exit code: 1

--- stderr
gyp ERR! build error
gyp ERR! stack Error: You must run `node-gyp configure` first!
gyp ERR! stack     at ReadFileContext.<anonymous> (/Users/jon/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:49:20)
gyp ERR! stack     at ReadFileContext.callback (/Users/jon/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
gyp ERR! stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:437:13)
gyp ERR! System Darwin 17.0.0
gyp ERR! command "/Users/jon/.nvm/versions/node/v9.5.0/bin/node" "/Users/jon/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /Users/jon/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-runtime-0.1.22
gyp ERR! node -v v9.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build-release: `node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jon/.npm/_logs/2018-02-10T21_26_17_157Z-debug.log
thread 'main' panicked at '

Internal error occurred: Command "ar" "crs" "/Users/jon/code/Experiments/threading-hint/native/target/release/build/neon-runtime-56ae8bb1d1629a4f/out/libneon.a" "build/Release/obj.target/neon/src/neon.o" with args "ar" did not execute successfully (status code exit code: 1).

', /Users/jon/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.54/src/lib.rs:1670:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/Users/jon/code/Experiments/threading-hint/node_modules/neon-cli/lib/target.js:124:35)
    at step (/Users/jon/code/Experiments/threading-hint/node_modules/neon-cli/lib/target.js:32:23)
    at Object.next (/Users/jon/code/Experiments/threading-hint/node_modules/neon-cli/lib/target.js:13:53)
    at fulfilled (/Users/jon/code/Experiments/threading-hint/node_modules/neon-cli/lib/target.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! threading-hint@0.1.0 install: `neon build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the threading-hint@0.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jon/.npm/_logs/2018-02-10T21_26_17_260Z-debug.log
```

# Npm debug log
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/jon/.nvm/versions/node/v9.5.0/bin/node',
1 verbose cli   '/Users/jon/.nvm/versions/node/v9.5.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build-release' ]
2 info using npm@5.6.0
3 info using node@v9.5.0
4 verbose run-script [ 'prebuild-release', 'build-release', 'postbuild-release' ]
5 info lifecycle @~prebuild-release: @
6 info lifecycle @~build-release: @
7 verbose lifecycle @~build-release: unsafe-perm in lifecycle true
8 verbose lifecycle @~build-release: PATH: /Users/jon/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/jon/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-runtime-0.1.22/node_modules/.bin:/Users/jon/.cargo/bin:/Users/jon/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/jon/code/Experiments/threading-hint/node_modules/.bin:/Users/jon/.rvm/gems/ruby-2.4.1/bin:/Users/jon/.rvm/gems/ruby-2.4.1@global/bin:/Users/jon/.rvm/rubies/ruby-2.4.1/bin:/Users/jon/.pyenv/plugins/pyenv-virtualenv/shims:/Users/jon/.pyenv/shims:/Users/jon/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jon/.rvm/gems/ruby-2.4.1/bin:/Users/jon/.rvm/gems/ruby-2.4.1@global/bin:/Users/jon/.rvm/rubies/ruby-2.4.1/bin:/Users/jon/.pyenv/plugins/pyenv-virtualenv/shims:/Users/jon/.pyenv/shims:/Users/jon/.cargo/bin:/Users/jon/.nvm/versions/node/v9.5.0/bin:/Users/jon/.fzf/bin:~/bin/:/usr/local/opt/postgresql@9.6/bin/:/Users/jon/.rvm/bin:~/bin/:/usr/local/opt/postgresql@9.6/bin/:/Users/jon/.rvm/bin
9 verbose lifecycle @~build-release: CWD: /Users/jon/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-runtime-0.1.22
10 silly lifecycle @~build-release: Args: [ '-c', 'node-gyp build' ]
11 silly lifecycle @~build-release: Returned: code: 1  signal: null
12 info lifecycle @~build-release: Failed to exec build-release script
13 verbose stack Error: @ build-release: `node-gyp build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/jon/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/jon/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid @
15 verbose cwd /Users/jon/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-runtime-0.1.22
16 verbose Darwin 17.0.0
17 verbose argv "/Users/jon/.nvm/versions/node/v9.5.0/bin/node" "/Users/jon/.nvm/versions/node/v9.5.0/bin/npm" "run" "build-release"
18 verbose node v9.5.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error @ build-release: `node-gyp build`
22 error Exit status 1
23 error Failed at the @ build-release script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

# Resolutions attempted

1. Re-installing neon
2. Re-installing node from nvm
3. Manually installing `node-gyp` and running `node-gyp configure`
4. Tried with node version `8.9.4` via nvm
5. Ran `rustup update` to update rustc to `rustc 1.25.0-nightly (3bcda48a3 2018-02-09)`

**Comment by jacobwgillespie** [comment]
Just ran into this issue - it looks like neon uses `node-gyp`, `node-gyp` in turn uses Python, and nowadays `brew install python` on macOS is installing Python 3, which isn't compatible with `node-gyp`.

I was able to solve this by doing the following:

1. `brew install python@2`
1. `virtualenv env`
1. `source env/bin/activate`
1. now neon builds as expected

**Comment by tptee** [comment]
Yikes, this is a really unfortunate change on Homebrew's part. Maybe we can just add this caveat to the docs @dherman ?

**Comment by dherman** [comment]
Ouch! (Yet another reason why it'd be good to get to a point where Neon libs could dynamically load the neon runtime as a DLL, and possibly avoid having to use `node-gyp` entirely?)

Anyway yes, I agree @tptee -- the thing to do is to update the docs (including the setup guide). I'll mark this issue as resolved but file an issue specifically for that.
