### ISSUE TITLE
Error: Module did not self-register after application packaging using pkg or nexe

### ISSUE THREAD

**Issue by justnoxx** [neon-bindings/neon#309]
I have an issue that is very similar to https://github.com/neon-bindings/neon/issues/265 but for pkg and nexe.

When I trying to package neon node application using pkg utility, it throws an exception "module did not self-register"
Just

```
node lib/index.js
```

works fine.

To reproduce just need to create simplest neon module using neon new, then compile it and check, using command node lib/index.js, it should be working

Then build it using pkg with proper target:

```
pkg --target node8-win-x64 lib/index.js
```
And run:

```
index.exe
```

As result:
```
pkg/prelude/bootstrap.js:1172
      throw error;
      ^

Error: Module did not self-register.
    at Object.Module._extensions..node (module.js:662:18)
    at Module.load (module.js:552:32)
    at tryModuleLoad (module.js:495:12)
    at Function.Module._load (module.js:487:3)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1153:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\snapshot\work\helloworld\lib\index.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:644:10)
```

I know, that it is the possible not a neon issue, but exactly the same behavior is what I have using nexe, but error is slightly different:

```
C:\work\helloworld>helloworld.exe
module.js:681
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at u (C:\work\helloworld\helloworld.exe:37:1092)
    at f (C:\work\helloworld\helloworld.exe:37:1344)
    at c (C:\work\helloworld\helloworld.exe:37:2731)
    at b.require (C:\work\helloworld\helloworld.exe:37:3327)
```

I will continue my investigation and will let you know if I find something.

**Comment by itserg2008** [comment]
I have exactly the same issue when running my Electron app on Windows 10. Has anyone resolved it somehow? I found a solution here (https://stackoverflow.com/questions/28486891/uncaught-error-module-did-not-self-register) but don't have an idea what exactly should be changed in neon to implement something like this:

void Init(v8::Handlev8::Object exports) {
NODE_SET_METHOD(exports, "method", method);
}

NODE_MODULE(method, Init);

**Comment by justnoxx** [comment]
I am sorry, I forgot to provide an update for this issue.
Looks like I found kinda reason of this error.
@itserg2008, it is because of updated node.js binaries that are being used for pkg. They are somehow different near the dlopen function. That's why it breaks. For now we using an embedded node for windows systems and pkg on linux/osx.
