### ISSUE TITLE
neon build fails on node v8.11.3

### ISSUE THREAD

**Issue by kanekv** [neon-bindings/neon#340]
```
root@404d40923172:/rust# node --version
v8.11.3

root@404d40923172:/rust# rustc --version
rustc 1.29.0-nightly (874dec25e 2018-07-21)
```

```
error: failed to run custom build command for `neon-runtime v0.1.23`
process didn't exit successfully: `/rust/native/target/release/build/neon-runtime-47c609a758991912/build-script-build` (exit code: 101)
--- stdout
up to date in 0.938s

> @ build-release /root/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-runtime-0.1.23
> node-gyp build

make: Entering directory '/root/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-runtime-0.1.23/build'
make: Leaving directory '/root/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-runtime-0.1.23/build'
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
AR_x86_64-unknown-linux-gnu = None
AR_x86_64_unknown_linux_gnu = None
HOST_AR = None
AR = None
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
running: "ar" "crs" "/rust/native/target/release/build/neon-runtime-843cd0f96f8884e4/out/libneon.a" "build/Release/obj.target/neon/src/neon.o"
cargo:warning=ar: build/Release/obj.target/neon/src/neon.o: No such file or directory
exit code: 1

--- stderr
make: *** No targets specified and no makefile found.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.49-moby
gyp ERR! command "/nodejs/bin/node" "/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /root/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-runtime-0.1.23
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build-release: `node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Kane-Sendgrid** [comment]
It seems it here: https://github.com/neon-bindings/neon/blob/master/crates/neon-runtime/package.json#L10

nan should be in dependencies section instead of devDependencies, after I move it there - it compiles.

**Comment by Lin-H** [comment]
I have the similar problem
window 7 64bit
node 8.11.3
Rust 1.27.2 stable msvc
```
LINK : fatal error LNK1181: cannot open input file 'build\Release\obj\neon\neon.obj'
exit code: 1181
```
haven't solve it yet :cry:

**Comment by jjpe** [comment]
Has anything been done with this yet?

**Comment by kjvalencik** [comment]
This was fixed in 367.
