### ISSUE TITLE
[win10] neon project breaks during build due to broken source code in neon.cc

### ISSUE THREAD

**Issue by JoeyAcc** [neon-bindings/neon#350]
When I try to use `neon 0.2.0` in combination with `node 8.9.0` (this issue also occurs when using `node 8.0.0`), neon juist fails to build without any good reason from my perspective, as it looks like there are internal inconsistencies within the neon codebase itself

UPDATE: the same error occurs with `neon 0.1.20`.

Here's the build log:

````
Microsoft Windows [Version 10.0.16299.371]
(c) 2017 Microsoft Corporation. Alle rechten voorbehouden.

C:\Users\foo>cd accept\sbr-validate-npm

C:\Users\foo\accept\sbr-validate-npm>npm i

> sbr-validate-npm@0.8.0 install C:\Users\foo\accept\sbr-validate-npm
> neon build

neon info forcing rebuild for new build settings
neon info running cargo
   Compiling nodrop v0.1.12
   Compiling cfg-if v0.1.4
   Compiling void v1.0.2
   Compiling scopeguard v0.3.3
   Compiling memoffset v0.2.1
   Compiling libc v0.2.43
   Compiling ucd-util v0.1.1
   Compiling matches v0.1.7
   Compiling itoa v0.4.2
   Compiling dtoa v0.4.3
   Compiling unicode-normalization v0.1.7
   Compiling rustc-demangle v0.1.9
   Compiling utf8-ranges v1.0.0
   Compiling percent-encoding v1.0.1
   Compiling either v1.5.0
   Compiling bitflags v1.0.3
   Compiling unicode-width v0.1.5
   Compiling xml-rs v0.8.0
   Compiling unicode-segmentation v1.2.1
   Compiling semver-parser v0.7.0
   Compiling glob v0.2.11
   Compiling cslice v0.2.0
   Compiling winapi v0.3.5
   Compiling num-traits v0.2.5
   Compiling num-integer v0.1.39
   Compiling serde v1.0.71
   Compiling rayon-core v1.4.1
   Compiling regex v1.0.2
   Compiling arrayvec v0.4.7
   Compiling unicode-bidi v0.3.4
   Compiling unreachable v1.0.0
   Compiling unreachable v0.1.1
   Compiling memchr v2.0.1
   Compiling num_cpus v1.8.0
   Compiling regex-syntax v0.6.2
   Compiling crossbeam-utils v0.2.2
   Compiling itertools v0.7.8
   Compiling lazy_static v1.1.0
   Compiling rayon v1.0.2
   Compiling semver v0.9.0
   Compiling smallvec v0.6.4
   Compiling aho-corasick v0.6.6
   Compiling smallstr v0.1.0
   Compiling neon-runtime v0.2.0 (file:///C:/Users/foo/accept/neon/crates/neon-runtime)
   Compiling crossbeam-epoch v0.3.1
   Compiling thread_local v0.3.5
   Compiling colored v1.6.1
   Compiling num-traits v0.1.43
   Compiling crossbeam-deque v0.2.0
   Compiling ordered-float v0.5.0
error: failed to run custom build command for `neon-runtime v0.2.0 (file:///C:/Users/foo/accept/neon/crates/neon-runtime)`
process didn't exit successfully: `C:\Users\foo\accept\sbr-validate-npm\native\target\release\build\neon-runtime-5e32bc85bb3b3375\build-script-build` (exit code: 101)
--- stdout
'Skipping node-gyp installation as part of npm install.'
up to date in 0.744s
cargo:node_arch=x64
cargo:node_root_dir=C:\\Users\\fop\\.node-gyp\\8.9.0
cargo:node_lib_file=C:\\Users\\foo\\.node-gyp\\8.9.0\\<(target_arch)\\node.lib

> @ build-release C:\Users\foo\accept\neon\crates\neon-runtime
> node-gyp build


C:\Users\foo\accept\neon\crates\neon-runtime>if not defined npm_config_node_gyp (node "C:\nvm\v8.9.0\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build )  else (node "" build )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  neon.cc
..\src\neon.cc(257): error C2275: 'v8::HandleScope' : illegal use of this type as an expression [C:\Users\foo\accept\neon\crates\neon-runtime\build\neon.vcxproj]
..\src\neon.cc(257): error C3861: 'alignof': identifier not found [C:\Users\foo\accept\neon\crates\neon-runtime\build\neon.vcxproj]
..\src\neon.cc(265): error C2275: 'v8::EscapableHandleScope' : illegal use of this type as an expression [C:\Users\foo\accept\neon\crates\neon-runtime\build\neon.vcxproj]
..\src\neon.cc(265): error C3861: 'alignof': identifier not found [C:\Users\foo\accept\neon\crates\neon-runtime\build\neon.vcxproj]
TARGET = Some("x86_64-pc-windows-msvc")
running: "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\bin\\amd64\\lib.exe" "/OUT:C:\\Users\\foo\\accept\\sbr-validate-npm\\native\\target\\x86_64-pc-windows-msvc\\release\\build\\neon-runtime-38d0d2355562f62c\\out\\libneon.a" "/nologo" "build\\Release\\obj\\neon\\neon.obj"
LINK : fatal error LNK1181: cannot open input file 'build\Release\obj\neon\neon.obj'
exit code: 1181

--- stderr
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\nvm\v8.9.0\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\nvm\\nodejs\\node.exe" "C:\\nvm\\v8.9.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd C:\Users\foo\accept\neon\crates\neon-runtime
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build-release: `node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\foo\AppData\Roaming\npm-cache\_logs\2018-08-08T10_07_57_858Z-debug.log
thread 'main' panicked at '

Internal error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\bin\\amd64\\lib.exe" "/OUT:C:\\Users\\foo\\accept\\sbr-validate-npm\\native\\target\\x86_64-pc-windows-msvc\\release\\build\\neon-runtime-38d0d2355562f62c\\out\\libneon.a" "/nologo" "build\\Release\\obj\\neon\\neon.obj" with args "lib.exe" did not execute successfully (status code exit code: 1181).

', C:\Users\foo\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.54\src\lib.rs:1670:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...

````

**Comment by kjvalencik** [comment]
It's not clear why this was happening. Since we currently have passing windows builds and this issue is a bit stale, I am closing. However, please re-open if this continues to be an issue!
