### ISSUE TITLE
build error of simple example

### ISSUE THREAD

**Issue by blaazetech** [neon-bindings/neon#364]
Am trying to build simple example given in hello-world example, but its giving error.
```
[root@sandbox threading-hint]# neon build
neon info running cargo
   Compiling threading-hint v0.1.0 (file:///home/ec2-user/threading-hint/native)                                                                                                                                   
error[E0432]: unresolved import `neon::vm`
 --> src/lib.rs:5:11
  |
5 | use neon::vm::{Call, JsResult};
  |           ^^ Could not find `vm` in `neon`

error[E0432]: unresolved import `neon::js`
 --> src/lib.rs:6:11
  |
6 | use neon::js::JsNumber;
  |           ^^ Could not find `js` in `neon`

error[E0599]: no method named `export` found for type `neon::context::ModuleContext<'_>` in the current scope
  --> src/lib.rs:13:7
   |
13 |     m.export("threading_hint", threading_hint)
   |       ^^^^^^

error: aborting due to 3 previous errors

Some errors occurred: E0432, E0599.
For more information about an error, try `rustc --explain E0432`.
error: Could not compile `threading-hint`.

To learn more, run the command again with --verbose.
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/usr/lib/node_modules/neon-cli/lib/target.js:121:35)
    at step (/usr/lib/node_modules/neon-cli/lib/target.js:32:23)
    at Object.next (/usr/lib/node_modules/neon-cli/lib/target.js:13:53)
    at fulfilled (/usr/lib/node_modules/neon-cli/lib/target.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by kjvalencik** [comment]
Hi, thanks for the report! This looks like an example that hasn't been updated for `v0.2`. You can find some more up to date examples in the [tests](https://github.com/neon-bindings/neon/tree/master/test/dynamic). IIRC, there are a couple of tickets for updating the examples.

**Comment by amilajack** [comment]
@blaazetech Please follow the [new guide here](https://neon-bindings.com/docs/hello-world). This should be closed

**Comment by kjvalencik** [comment]
I'm unable to find this outdated example. Please let me know if you can still find this linked from somewhere!
