### ISSUE TITLE
"Error: Module did not self-register." in Electron 4.0.1 on Windows(but works fine in 3.1.1)

### ISSUE THREAD

**Issue by Syndim** [neon-bindings/neon#389]
OS: Windows 10 1809
Rust version: 1.32.0 x86_64 MSVC
Electron version: 4.0.1
Neon binding version: 0.2.0
Node.js version: 10.15.0

How to reproduce:
1. Clone the neon-binding example repo: `https://github.com/neon-bindings/examples`
2. Change the electron version from `3.0.10` to `4.0.1` in packages.json under `electron-app`
3. `yarn` and then `yarn start`

Got the following log in the electron window:

```
Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object. (C:\examples\electron-app\node_modules\neon-hello\lib\index.js:1:168)
    at Object. (C:\examples\electron-app\node_modules\neon-hello\lib\index.js:5:3)
```

It doesn't reproduce under electron v3, is there any way to debug what's happening?

**Comment by amilajack** [comment]
Considering that `4.0.1` is a pretty recent major server of electron, it is likely that this might be an electron issue.

**Comment by itserg2008** [comment]
I have the same error even in 3.1.1. Tried to downgrade to this version but got the same error.

**Comment by itserg2008** [comment]
As I made a build using --release flag, I found the solution: here it is https://github.com/katyo/neon/commit/3319c6ce54ba67451b236901ca0669397d68c659

**Comment by itserg2008** [comment]
I see exactly the same behaviour - works fine for me on Windows 10 with Electron 3.0.10, but couldn't get it work on 4.0.X.

Any ideas?

**Comment by jrd-rocks** [comment]
In my own project i have the same problem. Electron 4.1.4 gives the error above. Downgrading to electron 3.1.8 and it works. Definitely something weird going on.

**Comment by jrd-rocks** [comment]
And  I got it working. See https://github.com/jrd-rocks/neon/blob/electron_delay_hook/README%20ELECTRON%204.md

#404

**Comment by itserg2008** [comment]
> And I got it working. See https://github.com/jrd-rocks/neon/blob/electron_delay_hook/README%20ELECTRON%204.md
> 
> #404

Wow, it's amazing! Have you created a pull request to the upstream branch?
