### ISSUE TITLE
Neon build still broken MacOS

### ISSUE THREAD

**Issue by timurista** [neon-bindings/neon#395]
Followed these steps in getting started guide
```npm install --global neon-cli
neon build
neon new threading-hint
```

my system info:
```
macOS 10.13.6 

python --version
Python 2.7.15 // after brew install python@2

node -v
v8.9.4 // managed with nvm 0.33.0

cargo --version
cargo 1.32.0 (8610973aa 2019-01-02)

rustc --version
rustc 1.32.0 (9fda7c223 2019-01-16)
```

PROBLEM on build step 20:
```
> neon build

Updating crates.io index
   Compiling memchr v2.2.0
   Compiling lazy_static v1.2.0
   Compiling ucd-util v0.1.3
   Compiling regex v0.2.11
   Compiling utf8-ranges v1.0.2
   Compiling gcc v0.3.55
   Compiling neon-build v0.2.0
   Compiling semver-parser v0.7.0
   Compiling cslice v0.2.0
   Compiling thread_local v0.3.6
   Compiling regex-syntax v0.5.6
   Compiling neon v0.2.0
   Compiling threading-hint v0.1.0 (/Users/timurista/projects/rust-examples/threading-hint/native)
   Compiling semver v0.9.0
   Compiling aho-corasick v0.6.9
   Compiling neon-runtime v0.2.0
error: failed to run custom build command for `neon-runtime v0.2.0`
process didn't exit successfully: `/Users/timurista/projects/rust-examples/threading-hint/native/target/debug/build/neon-runtime-dd40f1d9beab69ba/build-script-build` (exit code: 101)
--- stdout
Skipping node-gyp installation as part of npm install.
up to date in 0.44s

> @ build-debug /Users/timurista/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-runtime-0.2.0
> node-gyp build --debug

make: Nothing to be done for `all'.
TARGET = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
AR_x86_64-apple-darwin = None
AR_x86_64_apple_darwin = None
HOST_AR = None
AR = None
TARGET = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
running: "ar" "crs" "/Users/timurista/projects/rust-examples/threading-hint/native/target/debug/build/neon-runtime-e7ed0bbd51c658b3/out/libneon.a" "build/Debug/obj.target/neon/src/neon.o"
cargo:warning=ar: build/Debug/obj.target/neon/src/neon.o:No such file or directory
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "ar" "crs" "/Users/timurista/projects/rust-examples/threading-hint/native/target/debug/build/neon-runtime-e7ed0bbd51c658b3/out/libneon.a" "build/Debug/obj.target/neon/src/neon.o" with args "ar" did not execute successfully (status code exit code: 1).

', /Users/timurista/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.55/src/lib.rs:1672:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/Users/timurista/.nvm/versions/node/v8.9.4/lib/node_modules/neon-cli/lib/target.js:121:35)
    at step (/Users/timurista/.nvm/versions/node/v8.9.4/lib/node_modules/neon-cli/lib/target.js:32:23)
    at Object.next (/Users/timurista/.nvm/versions/node/v8.9.4/lib/node_modules/neon-cli/lib/target.js:13:53)
    at fulfilled (/Users/timurista/.nvm/versions/node/v8.9.4/lib/node_modules/neon-cli/lib/target.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

What I tried
- reinstalling rust
- using python 2 instead of 3
- setting different reference: `export NODEJS_ORG_MIRROR=$NVM_NODEJS_ORG_MIRROR`

**Comment by kjvalencik** [comment]
It looks like it's failing to build `neon-runtime`, but the actual messages are getting suppressed. Could you try cloning this repo and building `neon-runtime` directly? Unfortunately, I don't have a mac to test.

```sh
git clone https://github.com/neon-bindings/neon.git
cd neon/crates/neon-runtime
cargo build
```

**Comment by timurista** [comment]
@kjvalencik 	
Those steps seem to pass....
 ```
> cargo build   Thu Feb 14 06:34:07 2019
    Updating crates.io index
  Downloaded cc v1.0.29
  Downloaded regex v1.1.0
  Downloaded regex-syntax v0.6.5
   Compiling memchr v2.2.0
   Compiling regex v1.1.0
   Compiling ucd-util v0.1.3
   Compiling lazy_static v1.2.0
   Compiling utf8-ranges v1.0.2
   Compiling cc v1.0.29
   Compiling thread_local v0.3.6
   Compiling regex-syntax v0.6.5
   Compiling aho-corasick v0.6.9
   Compiling neon-runtime v0.2.0 (/Users/timurista/projects/neon/crates/neon-runtime)
    Finished dev [unoptimized + debuginfo] target(s) in 23.40s
```

**Comment by timurista** [comment]
but sadly threading hint still fails now with the gyp NVM_NODEJS_ORG_MIRROR error:
```
threading-hint $ npm i

> threading-hint@0.1.0 install /Users/timurista/projects/rust-examples/threading-hint
> neon build

neon info forcing rebuild for new build settings
neon info running cargo
   Compiling memchr v2.2.0
   Compiling lazy_static v1.2.0
   Compiling ucd-util v0.1.3
   Compiling regex v0.2.11
   Compiling utf8-ranges v1.0.2
   Compiling gcc v0.3.55
   Compiling neon-build v0.2.0
   Compiling semver-parser v0.7.0
   Compiling cslice v0.2.0
   Compiling thread_local v0.3.6
   Compiling regex-syntax v0.5.6
   Compiling neon v0.2.0
   Compiling threading-hint v0.1.0 (/Users/timurista/projects/rust-examples/threading-hint/native)
   Compiling semver v0.9.0
   Compiling aho-corasick v0.6.9
   Compiling neon-runtime v0.2.0
error: failed to run custom build command for `neon-runtime v0.2.0`
process didn't exit successfully: `/Users/timurista/projects/rust-examples/threading-hint/native/target/debug/build/neon-runtime-dd40f1d9beab69ba/build-script-build` (exit code: 101)
--- stdout
Skipping node-gyp installation as part of npm install.
up to date in 0.468s

> @ build-debug /Users/timurista/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-runtime-0.2.0
> node-gyp build --debug

make: Nothing to be done for `all'.
TARGET = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
AR_x86_64-apple-darwin = None
AR_x86_64_apple_darwin = None
HOST_AR = None
AR = None
TARGET = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
running: "ar" "crs" "/Users/timurista/projects/rust-examples/threading-hint/native/target/debug/build/neon-runtime-e7ed0bbd51c658b3/out/libneon.a" "build/Debug/obj.target/neon/src/neon.o"
cargo:warning=ar: build/Debug/obj.target/neon/src/neon.o: No such file or directory
exit code: 1

--- stderr
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
thread 'main' panicked at '

Internal error occurred: Command "ar" "crs" "/Users/timurista/projects/rust-examples/threading-hint/native/target/debug/build/neon-runtime-e7ed0bbd51c658b3/out/libneon.a" "build/Debug/obj.target/neon/src/neon.o" with args "ar" did not execute successfully (status code exit code: 1).

', /Users/timurista/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.55/src/lib.rs:1672:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/Users/timurista/projects/rust-examples/threading-hint/node_modules/neon-cli/lib/target.js:121:35)
    at step (/Users/timurista/projects/rust-examples/threading-hint/node_modules/neon-cli/lib/target.js:32:23)
    at Object.next (/Users/timurista/projects/rust-examples/threading-hint/node_modules/neon-cli/lib/target.js:13:53)
    at fulfilled (/Users/timurista/projects/rust-examples/threading-hint/node_modules/neon-cli/lib/target.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! threading-hint@0.1.0 install: `neon build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the threading-hint@0.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/timurista/.npm/_logs/2019-02-14T14_38_28_505Z-debug.log
```

**Comment by kjvalencik** [comment]
It's still the same error, `cargo:warning=ar: build/Debug/obj.target/neon/src/neon.o: No such file or directory`.

Does `neon.o` exist anywhere else and the path is just wrong?

```sh
find -name 'neon.o'
```

**Comment by timurista** [comment]
@kjvalencik 	thanks the problem was npm install. Needed this `npm install --global --save neon-cli` I was missing neon.o. 👍
