### ISSUE TITLE
Issue compiling on macOS

### ISSUE THREAD

**Issue by galvez** [neon-bindings/neon#397]
Running `neon build`:

```
error: associated constants are experimental (see issue #29646)
  --> /Users/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.3.0/src/inline_lazy.rs:20:5
   |
20 |     pub const INIT: Self = Lazy(Cell::new(None), ONCE_INIT);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `lazy_static`.
Build failed, waiting for other jobs to finish...
error: cannot find macro `eprintln!` in this scope
 --> /Users/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/memchr-2.2.0/build.rs:9:13
  |
9 |             eprintln!("failed to parse `rustc --version`: {}", err);
  |             ^^^^^^^^
  |
  = help: did you mean `println!`?

error: aborting due to previous error
```

Anyone seen this?

**Comment by galvez** [comment]
So I updated rustc to the latest version and one of these errors is gone. Still getting:

```
aurelius:gateway jonas$ neon build
neon info forcing rebuild for new build settings
neon info running cargo
   Compiling cslice v0.2.0
   Compiling semver-parser v0.7.0
   Compiling utf8-ranges v1.0.2
   Compiling neon-build v0.2.0
   Compiling neon v0.2.0
   Compiling lazy_static v1.3.0
error: associated constants are experimental (see issue #29646)
  --> /Users/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.3.0/src/inline_lazy.rs:20:5
   |
20 |     pub const INIT: Self = Lazy(Cell::new(None), ONCE_INIT);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `lazy_static`.
Build failed, waiting for other jobs to finish...
error: build failed
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/Users/jonas/.config/yarn/global/node_modules/neon-cli/lib/target.js:121:35)
    at step (/Users/jonas/.config/yarn/global/node_modules/neon-cli/lib/target.js:32:23)
    at Object.next (/Users/jonas/.config/yarn/global/node_modules/neon-cli/lib/target.js:13:53)
    at fulfilled (/Users/jonas/.config/yarn/global/node_modules/neon-cli/lib/target.js:4:58)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**Comment by galvez** [comment]
Turns out my Rust version wasn't really up to date.

```
rustup override set 1.33.0
```

Did the trick.
