### ISSUE TITLE
Build fails on Windows 10 (neon-examples)

### ISSUE THREAD

**Issue by ciyool** [neon-bindings/neon#399]
OS: Windows 10.0.17763
Rust version: 1.33.0 x86_64 MSVC
Node.js: v10.15.2
npm: 6.4.1
yarn: 1.15.2
Python: 2.7.15
toolchain: stable-x86_64-pc-windows-msvc (default)

git clone https://github.com/neon-bindings/examples
cd examples
cd primitives
npm install # OR `yarn`

```rust
$ yarn
yarn install v1.15.2
[1/4] Resolving packages...
success Already up-to-date.
$ neon build
neon info forcing rebuild for new build settings
neon info running cargo
   Compiling memchr v2.2.0
   Compiling ucd-util v0.1.3
   Compiling lazy_static v1.3.0
   Compiling regex v0.2.11
   Compiling utf8-ranges v1.0.2
   Compiling gcc v0.3.55
   Compiling neon-build v0.2.0
   Compiling semver-parser v0.7.0
   Compiling cslice v0.2.0
   Compiling thread_local v0.3.6
   Compiling neon v0.2.0
   Compiling test2 v0.1.0 (E:\Project\Ciyool\Rust_Electron\Rust\test2\native)
   Compiling regex-syntax v0.5.6
   Compiling semver v0.9.0
   Compiling aho-corasick v0.6.10
   Compiling neon-runtime v0.2.0
error: failed to run custom build command for `neon-runtime v0.2.0`
process didn't exit successfully: `E:\Project\Ciyool\Rust_Electron\Rust\test2\native\target\debug\build\neon-runtime-5cc58d93b4f7ca1a\build-script-build` (exit code: 101)
--- stderr
gyp ERR! build error
gyp ERR! stack Error: Could not find *.sln file. Did you run "configure"?
gyp ERR! stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:93:25
gyp ERR! stack     at f (D:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
gyp ERR! stack     at Glob.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\glob\glob.js:151:7)
gyp ERR! stack     at Glob.emit (events.js:189:13)
gyp ERR! stack     at Glob._finish (D:\Program Files\nodejs\node_modules\npm\node_modules\glob\glob.js:197:8)
gyp ERR! stack     at done (D:\Program Files\nodejs\node_modules\npm\node_modules\glob\glob.js:182:14)
gyp ERR! stack     at Glob._processReaddir2 (D:\Program Files\nodejs\node_modules\npm\node_modules\glob\glob.js:408:12)
gyp ERR! stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\glob\glob.js:371:17
gyp ERR! stack     at RES (D:\Program Files\nodejs\node_modules\npm\node_modules\inflight\inflight.js:31:16)
gyp ERR! stack     at f (D:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--debug"
gyp ERR! cwd C:\Users\ciyoo\.cargo\registry\src\github.com-1ecc6299db9ec823\neon-runtime-0.2.0
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build-debug: `node-gyp build --debug`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build-debug script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ciyoo\AppData\Roaming\npm-cache\_logs\2019-03-29T17_50_10_450Z-debug.log
thread 'main' panicked at '

Internal error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\lib.exe" "/OUT:E:\\Project\\Ciyool\\Rust_Electron\\Rust\\test2\\native\\target\\x86_64-pc-windows-msvc\\debug\\build\\neon-runtime-46362ca95a06295e\\out\\libneon.a" "/nologo" "build\\Debug\\obj\\neon\\neon.obj" with args "lib.exe" did not execute successfully (status code exit code: 1181).

', C:\Users\ciyoo\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.55\src\lib.rs:1672:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (E:\Project\Ciyool\Rust_Electron\Rust\test2\node_modules\neon-cli\lib\target.js:121:35)
    at step (E:\Project\Ciyool\Rust_Electron\Rust\test2\node_modules\neon-cli\lib\target.js:32:23)
    at Object.next (E:\Project\Ciyool\Rust_Electron\Rust\test2\node_modules\neon-cli\lib\target.js:13:53)
    at fulfilled (E:\Project\Ciyool\Rust_Electron\Rust\test2\node_modules\neon-cli\lib\target.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by mefechoel** [comment]
The same issue

**Comment by yorodm** [comment]
I get a bunch of linker errors with the classes example
