### ISSUE TITLE
Undefined Symbol

### ISSUE THREAD

**Issue by shavz** [neon-bindings/neon#405]
Hi,

I'm trying to load a library build with neon in an app that uses `yarn --production` to install dependencies.

But when i try to load the neon dependency I get the following error:

```/usr/src/app/node_modules/@ordermentum/sundial-neon/native/index.node: undefined symbol: _ZN2v88Function3NewENS_5LocalINS_7ContextEEEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS1_IS5_EEiNS_19ConstructorBehaviorE
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)```

Have spent a lot of time trying to debug the issue but have hot a brick wall now and support would be very appreciated.

Thank you.

**Comment by shavz** [comment]
Update:

resolved the issue, it was being caused due to running the module inside a docker image containing node 10
