### ISSUE TITLE
Error: internal error in Neon module: attempt to subtract with overflow

### ISSUE THREAD

**Issue by PieerotGG** [neon-bindings/neon#415]
Hello !

I'm writing a neon library for my nodejs project. I'm using [rust-crypto](https://github.com/DaGenix/rust-crypto).

### Private functions definitions

```rust
pub fn in_encrypt(raw_data: String, raw_key: String) -> Result<(String, String), String>;
pub fn in_decrypt(encrypted_data: String, raw_key: String, raw_iv: String) -> Result<String, String>;
```

### Working / Passing test

```rust
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn encrypt_and_decrypt() {
        unsafe {
            let to_encrypt = "Hello World!";

            let mut key: [u8; 32] = [0; 32];

            let mut rng = OsRng::new().ok().unwrap();
            rng.fill_bytes(&mut key);

            let (encrypted_data, iv) = match in_encrypt(
                String::from(to_encrypt),
                String::from_utf8_unchecked(key.to_vec()),
            ) {
                Ok(res) => res,
                Err(err) => panic!("Encrypting error {}", err),
            };

            let decrypted_data = match in_decrypt(
                encrypted_data,
                String::from_utf8_unchecked(key.to_vec()),
                iv,
            ) {
                Ok(res) => res,
                Err(err) => panic!("Decrypting error {}", err),
            };
            assert_eq!(String::from(to_encrypt), decrypted_data)
        }
    }
}
```

### Neon rust functions

```rust
fn encrypt(mut cx: FunctionContext) -> JsResult<JsUndefined> {
    let raw_key = cx.argument::<JsString>(0)?.value();
    let raw_data = cx.argument::<JsString>(1)?.value();
    let callback = cx.argument::<JsFunction>(2)?;

    let (encrypted_data, iv) = match crypt::in_encrypt(raw_data, raw_key) {
        Ok(res) => res,
        Err(err) => panic!("{}", err)
    };

    let js_result = JsObject::new(&mut cx);

    let js_encrypted_data = cx.string(encrypted_data);
    let js_iv = cx.string(iv);

    js_result.set(&mut cx, "encryptedData", js_encrypted_data)?;
    js_result.set(&mut cx, "iv", js_iv)?;
    let nul = cx.null();

    callback.call(&mut cx, nul, vec![js_result])?;

    Ok(cx.undefined())
}

fn decrypt(mut cx: FunctionContext) -> JsResult<JsUndefined> {
    let encryped_data = cx.argument::<JsString>(0)?.value();
    let raw_key = cx.argument::<JsString>(1)?.value();
    let raw_iv = cx.argument::<JsString>(2)?.value();
    let callback = cx.argument::<JsFunction>(3)?;

    let decrypted_data = match crypt::in_decrypt(encryped_data, raw_key, raw_iv) {
        Ok(res) => res,
        Err(err) => panic!("{}", err)
    };

    let nul = cx.null();
    let js_decrypted_data = cx.string(decrypted_data);

    callback.call(&mut cx, nul, vec![js_decrypted_data])?;

    Ok(cx.undefined())
}
```

### Neon nodejs functions call
```js
var addon = require('../native');

const SECRET = 'secret_key'
const TO_ENCRYPT = 'Hello World!'

console.log(`encrypting: ${TO_ENCRYPT}`)

addon.encrypt(SECRET, TO_ENCRYPT, ({ encryptedData, iv }) => {
	console.log(`Encrypted data: ${encryptedData} with iv: ${iv}`)

	addon.decrypt(encryptedData, SECRET, iv, (decrypted) => {
		console.log(`Decrypted data: ${decrypted}`)
	})
})
```

When I run `cargo test --release` my functions are working but when i run `node -e 'require("./")'` the following error is thrown

```
/home/pierre/Documents/dev/passe-muraille/Libs/pm-crypto/lib/index.js:11
        addon.decrypt(encryptedData, SECRET, iv, (decrypted) => {
              ^

Error: internal error in Neon module: attempt to subtract with overflow
    at addon.encrypt (/home/pierre/Documents/dev/passe-muraille/Libs/pm-crypto/lib/index.js:11:8)
    at Object.<anonymous> (/home/pierre/Documents/dev/passe-muraille/Libs/pm-crypto/lib/index.js:8:7)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:124:20)
```

Is there a way to see the stacktrace or do you know why this happens ?

Thank you for your time !

**Comment by kjvalencik** [comment]
Do you have this issue if you run `cargo test` without `--release`? Overflow detection is disabled in release builds for performance.
