### ISSUE TITLE
Error: cannot find module '../native'

### ISSUE THREAD

**Issue by digital-nomad17** [neon-bindings/neon#428]
Working through the tutorial code and I run into this error
```
> var threadCount = require('.')
Thrown:
{ Error: Cannot find module '../native'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18) code: 'MODULE_NOT_FOUND' }
```
Maybe there's something wrong with my configuration:

OS: Windows 10 
Rust ver:1.37.0
neon: 0.31
ide:clion with rust plugin

**Comment by digital-nomad17** [comment]
I get this error when I run `neon build`

```
error: Neon only builds with --release. For tests, try `cargo test --release`.
   --> C:\Users\Andrew\.cargo\registry\src\github.com-1ecc6299db9ec823\neon-0.3.1\src\lib.rs:292:1
    |
292 | compile_error!("Neon only builds with --release. For tests, try `cargo test --release`.");
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `neon`.

To learn more, run the command again with --verbose.
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (F:\Code\rust\neon_demo\thread-count\node_modules\neon-cli\lib\target.js:124:35)
    at step (F:\Code\rust\neon_demo\thread-count\node_modules\neon-cli\lib\target.js:32:23)
    at Object.next (F:\Code\rust\neon_demo\thread-count\node_modules\neon-cli\lib\target.js:13:53)
    at fulfilled (F:\Code\rust\neon_demo\thread-count\node_modules\neon-cli\lib\target.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

Here's my `package.json`:
```
{
  "name": "thread-count",
  "version": "0.1.0",
  "description": "demo",
  "main": "lib/index.js",
  "author": "",
  "license": "MIT",
  "dependencies": {
    "neon-cli": "^0.3.1"
  },
  "scripts": {
    "install": "neon build"
  }
}

```

**Comment by adumbidiot** [comment]
Try running `neon build —release`

**Comment by usagi** [comment]
I have an interested to this issue related from #463 . But, I think this situation could be solved with @adumbidiot 's proposal nor you @digital-nomad17 was solved the problem but you forgetting to close this issue. 😄 Would you close it or please share an additional infos?

---
Related: #463 "No way to build without --release?"

**Comment by kjvalencik** [comment]
Closing as a duplicate.
