### ISSUE TITLE
node child_process throws error: stdout maxBuffer length exceeded

### ISSUE THREAD

**Issue by marcmo** [neon-bindings/neon#456]
I recently upgraded from 0.3.1 to 0.3.2 and now I get an error when running the node command
`neon build --release`
```
2019-10-21T13:14:49.3886430Z > electron-build-env neon build --release
2019-10-21T13:14:49.3886890Z 
2019-10-21T13:14:52.9685910Z neon ERR! stdout maxBuffer length exceeded
2019-10-21T13:14:52.9689120Z 
2019-10-21T13:14:52.9692510Z RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
2019-10-21T13:14:52.9692790Z     at Socket.onChildStdout (child_process.js:354:14)
2019-10-21T13:14:52.9693420Z     at Socket.emit (events.js:198:13)
2019-10-21T13:14:52.9693640Z     at addChunk (_stream_readable.js:288:12)
2019-10-21T13:14:52.9693840Z     at readableAddChunk (_stream_readable.js:265:13)
2019-10-21T13:14:52.9694080Z     at Socket.Readable.push (_stream_readable.js:224:10)
2019-10-21T13:14:52.9694290Z     at Pipe.onStreamRead (internal/stream_base_commons.js:94:17)
2019-10-21T13:14:52.9764480Z electron-build-env error
```

same build only with the older version 0.3.1 works without errors.
for reference: this is my repo with the builds that are failing:
![image](https://user-images.githubusercontent.com/99541/67219219-f2727500-f427-11e9-9f09-ae6ce9522d0a.png)

https://github.com/esrlabs/chipmunk/commit/c8e22e5794a9823e0bc6a9977326dbf71eee2162/checks?check_suite_id=270766268
exactly the same commit, but a different version neon-cli:
![image](https://user-images.githubusercontent.com/99541/67219195-e38bc280-f427-11e9-86f8-efc64fb105d8.png)

https://github.com/esrlabs/chipmunk/commit/c8e22e5794a9823e0bc6a9977326dbf71eee2162/checks?check_suite_id=273994690

**Comment by kjvalencik** [comment]
FYI https://github.com/neon-bindings/neon/pull/454/files

**Comment by gbenattar** [comment]
Impacting our infra as well. Last build was 6 minutes ago. Can we have an update?

**Comment by kjvalencik** [comment]
@gbenattar I might not have a chance to do a release today. As a stop gap, you should be able to safely downgrade `neon-cli` to `0.3.1` or use a git dependency pointed at master.

Thanks for your patience!

**Comment by kjvalencik** [comment]
`0.3.3` has been published with a hotfix.
