### ISSUE TITLE
Invalid access to memory location.

### ISSUE THREAD

**Issue by anurbol** [neon-bindings/neon#467]
So I made an addon with Neon. It works if I am requring it from a simple `.js` file. However, when it is required by [TypeScript compiler plugin](https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin) I get this error in the TS logs:

```
Info 33   [7:54:51.638] Failed to load module 'hypercomments-ts-lsplugin' from C:/Users/nurbol/AppData/Roaming/npm/node_modules/node_modules: Error: Invalid access to memory location.
\\?\C:\w\hc\server\builds\publish\index.node
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
```

The legacy C++ addon (which I am switching to Rust from) works though.

I've upgraded, downgraded everything: TypeScript, node.js, VSCode, nothing works. I've learned from Google that this is a binary error that happens in other languages like C++ or C#. I tried to log from the Rust code, but the error occurs before the first line gets executed, i.e. at the time of inclusion of the binary.

I am on Windows 7.

I am so desperate, I don't know what to do.

**Comment by anurbol** [comment]
This was fixed by switcthing to windows 10
