### ISSUE TITLE
"Module did not self-register"

### ISSUE THREAD

**Issue by anurbol** [neon-bindings/neon#468]
My addon is required by a Typescript [Plugin](https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin)

```
Failed to load module 'C:/w/hc/adapters/ts-lsplugin' from c:/Users/nurbol/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/node_modules: Error: Module did not self-register.
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:138:31)
```

Windows 10.

I tried using [this](https://github.com/jrd-rocks/neon/blob/electron_delay_hook/README%20ELECTRON%204.md) branch (neon v0.2), with no success. 

Neon is great for the most part, but this last error made me so unhappy. I've spent 5 weeks to rewrite the addon to Rust and neon, I don't know what to do know.

**Comment by anurbol** [comment]
At the moment I am too tired, and I only have the energy to make a guess that this error has something to do with the fact that VSCode, despite the fact that it's based on Electron, provides environment variables that are different from those [provided by Electron]([https://github.com/neon-bindings/neon/blob/72e83f0f4f11132710116b3491235e7c7310b193/crates/neon-build/src/lib.rs#L25]), namely, maybe it provides `npm_config_runtime` env variable other than `electron` or that env variable is empty. 

I am not sure at anything, though. 

I beg for help, @kjvalencik, @jrd-rocks

**Comment by anurbol** [comment]
I ran `npm config set runtime electron` and that error is gone, now I have 

```
The module '\\?\C:\w\hc\server\native\index.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 79. This version of Node.js requires
NODE_MODULE_VERSION 73. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

**Comment by anurbol** [comment]
Turns out it's [Electron](https://github.com/electron/electron/issues/21337) to blame. Neon itself seems to work fine.
