### ISSUE TITLE
Blank project does not build

### ISSUE THREAD

**Issue by wahur666** [neon-bindings/neon#592]
Using Windows 10 64bit, MSVC

I created a new project, no code added, and I ran `npm install`

```
Compiling neon-thread-count v0.1.0 (D:\Documents\Git\neon-thread-count\native)
    |
356 | compile_error!("Neon only builds with --release. For tests, try `cargo test --release`.");
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


error: could not compile `neon`.

To learn more, run the command again with --verbose.
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (D:\Documents\Git\neon-thread-count\node_modules\neon-cli\lib\target.js:121:35)
    at step (D:\Documents\Git\neon-thread-count\node_modules\neon-cli\lib\target.js:32:23)
    at Object.next (D:\Documents\Git\neon-thread-count\node_modules\neon-cli\lib\target.js:13:53)
    at fulfilled (D:\Documents\Git\neon-thread-count\node_modules\neon-cli\lib\target.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! neon-thread-count@0.1.0 install: `neon build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the neon-thread-count@0.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Imre5\AppData\Roaming\npm-cache\_logs\2020-08-27T07_04_27_279Z-debug.log
PS D:\Documents\Git\neon-thread-count> code .
PS D:\Documents\Git\neon-thread-count> npm run i
npm ERR! missing script: i

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Imre5\AppData\Roaming\npm-cache\_logs\2020-08-27T07_05_44_478Z-debug.log
```

Is this just for me? Maybe something mis-configured with the cli?

**Comment by wahur666** [comment]
Followup, I see that the webpage says: `neon build --release`,
but the cli output is `To build your project, just run npm install from within the neon-thread-count directory.` , 
and  best of all the script in the package.json has the following:

```js
"scripts": {
    "install": "neon build"
}
```

So what is it? The default cli configuration is clearly broken, please fix

**Comment by kjvalencik** [comment]
@wahur666 I'm closing issue since a fix preventing windows debug builds was [merged](https://github.com/neon-bindings/neon/pull/506). It will be available on the next release of neon or can be used now by specifying a git dependency.

I apologize that the default configuration is unclear. It was kept since this is a Windows only issue.
