### ISSUE TITLE
Exporting class, methods not found

### ISSUE THREAD

**Issue by jessbowers** [neon-bindings/neon#682]
I have a class that I'm exporting, but I'm not seeing any methods when trying to call them.

```rust
use neon::prelude::*;

pub struct Person {
    pub name: String,
}

declare_types! {

    /// JS class wrapping ConfigProvider.
    pub class JsPerson for Person {
        init(_cx) {
            Ok(Person {
                name : "world".to_string()
            })
        }

        method hello(mut ctx) -> JsResult<JsValue> {
            let this = cx.this();
            Ok(ctx.string(format!("hello {}", &this.name)).upcast())
        }
    }

}

// Export the class
register_module!(mut m, {
    // exposes MyClass in JS
    m.export_class::<JsPerson>("Person")
});
```

Running the following in node:
```js
var addon = require('../native');

const world = new addon.Person()
console.log(world.hello());
```

gives these errors…
```
node ./lib/index.js     
/Users/jbowers/tmp/thread-count/lib/index.js:4
console.log(world.hello());
                  ^

TypeError: world.hello is not a function
    at Object.<anonymous> (/Users/jbowers/tmp/thread-count/lib/index.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

Rust rustc 1.48.0
neon-cli 0.7.1
macOS 10.15.7
node v14.15.5

**Comment by kjvalencik** [comment]
@jessbowers This is an unfortunate side of macros. The `method hello` is not actually being compiled because it doesn't match. The macro is defined to _not_ expect a return type.

```diff
-         method hello(mut ctx) -> JsResult<JsValue> {
+         method hello(mut ctx) {
```

After this change, the code doesn't get removed. It produces a couple of errors:

```
error[E0425]: cannot find value `cx` in this scope
  --> src/lib.rs:18:24
   |
18 |             let this = cx.this();
   |                        ^^ help: a local variable with a similar name exists: `ctx`
   ```

Making the following changes, this works:

```rust
        method hello(mut cx) {
            let this = cx.this();
            let greeting = cx.borrow(&this, |this| format!("hello {}", &this.name));

            Ok(cx.string(greeting).upcast())
        }
```

**Comment by jessbowers** [comment]
thanks so much! yeah the macros are definitely obscuring things. Is there a way to turn on some kind of warning that logs when a method doesn't fit the pattern?

**Comment by kjvalencik** [comment]
Usually there would be a compiler error if it doesn't match. This must be matching, but the macro is discarding it.

I am hesitant to file a bug because the `declare_types` macro is deprecated. It is replaced with `JsBox` in the N-API backend and eventually a proc macro.
