### ISSUE TITLE
spawn cargo ENOENT on Ubuntu 20.10

### ISSUE THREAD

**Issue by justablob** [neon-bindings/neon#718]
Hey.

Just like a few other people here, I'm unable to run `neon build` because it's unable to find `cargo`, even though it's in my $PATH (only once). However, I'm running Ubuntu 20.10, not Windows like the other people who have (or had?) this issue. 

```
neon ERR! spawn cargo ENOENT

Error: spawn cargo ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Here's my $PATH and cargo location:

```
> echo $PATH
/home/chef/.nvm/versions/node/v16.0.0/bin:/home/chef/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/chef/.bin:/opt/dotnet:/home/chef/.config/yarn/global/node_modules/.bin
> ls -l $(which cargo)
-rwxr-xr-x 12 chef chef 12817272 Mär 29 07:01 /home/chef/.cargo/bin/cargo
```

Node.js version 16.0.0, although I'm also getting this same issue on v14.16.1 and v15.14.0. 
Cargo version 1.52.0-nightly.
Neon version 0.8.0.

**Comment by kjvalencik** [comment]
I'm unable to reproduce. If you run `cargo` in the `native` directory, does it work?

**Comment by justablob** [comment]
Yep, it works. Cargo prints it's usual help message.

**Comment by kjvalencik** [comment]
Can you share your `npm` version? `npm -v`

**Comment by justablob** [comment]
`npm -v`: `7.11.1`

**Comment by kjvalencik** [comment]
@justablob I wasn't able to reproduce this issue. I tried to match your environment as closely as possible, but everything was successful.

Let me know if any of these steps look significantly different from your environment:

```
# Start an Ubuntu container for ephemeral testing
docker run --rm -it ubuntu:20.10

# The rest of the commands are inside the container

# Install prerequisites
apt-get update
apt-get install -y curl build-essential python3

# Install Rust
# I picked the nightly toolchain and the rest were defaults
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# Install nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash

# cargo and nvm have been added to the bash profile, but it needs to be reloaded for the current session
source ~/.bashrc

# Install Node 16
nvm install 16

# Upgrade npm
npm install -g npm@7.11.1

# Install the neon CLI
npm install -g neon-cli

# Create a new project; used defaults
neon new my-project
cd my-project

# There is a known issue with Node 16, but it's fixed on `main`
# The issue is unrelated to the issue you are having. It would come after the failure mentioned previously.
# Manually updated `native/Cargo.toml` to use the unpublished branch:
# neon-build = { git = "https://github.com/neon-bindings/neon.git" }
# neon = { git = "https://github.com/neon-bindings/neon.git" }

# Test!
npm install
node .
# hello node
```

I'm otherwise unsure of what to test. Maybe it's the shell causing issues? What shell are you using?

**Comment by Ar37-rs** [comment]
i had similar issue, reinstall neon-cli and reinit (neon new). solved it.

**Comment by justablob** [comment]
@kjvalencik Pardon my late reply, I was away for a few days. Looking at that script, it's pretty similar to my setup. I'm using bash, Ubuntu's default shell.

**Comment by Rush** [comment]
Adding a `native` directory helped a bit. The code says:
```
let { crate = "native" } = options;
```

I created my project through an npm template which is perhaps broken.

now the error is:
```
Error: ENOENT: no such file or directory, open '/code/rush-images/native/Cargo.toml'
    at Object.readFileUtf8 (node:internal/fs/sync:25:18)
    at readFileSync (node:fs:441:19)
    at loadLibName (/code/rush-images/node_modules/neon-cli/lib/crate.js:54:63)
    at new Crate (/code/rush-images/node_modules/neon-cli/lib/crate.js:29:21)
    at new Project (/code/rush-images/node_modules/neon-cli/lib/project.js:27:22)
    at Project.<anonymous> (/code/rush-images/node_modules/neon-cli/lib/project.js:38:20)
    at Generator.next (<anonymous>)
    at fulfilled (/code/rush-images/node_modules/neon-cli/lib/project.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Comment by kjvalencik** [comment]
The npm template is kept up to date and should be working. Did you have any errors on `npm install`?

**Comment by Rush** [comment]
I believe I made a mistake by trying to use `neon build` and having the base directory created via the new npm template. I got very confused by the old way vs new way. :)

**Comment by kjvalencik** [comment]
Ah! That would make sense. `neon build` hasn't been recommended since the Node-API was made the default a couple years ago. It's not compatible with the directory structure that `npm init neon` generated.

**Comment by Rush** [comment]
The problem is that the error is very baffling. If possible, we could
detect the error and provide a suggested solution.

Damian "Rush" Kaczmarek
