### ISSUE TITLE
Neon panics when trying to throw an error

### ISSUE THREAD

**Issue by AnnikaCodes** [neon-bindings/neon#819]
While trying to throw an error with the following code snippet
```rust
let line = match line {
    Ok(s) => s,
    Err(e) => {
        let err_string = context.string(format!(
            "Error converting byte sequence to a string using UTF-8: {}",
            e
        ));
        if let Ok(_) = context.throw::<JsString, JsError>(err_string) {
            panic!("Unable to throw error");
        }
        return Ok(());
    }
};
```
Neon panics:
```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `PendingException`,
 right: `Ok`', /Users/annika/.cargo/registry/src/github.com-1ecc6299db9ec823/neon-runtime-0.9.1/src/napi/error.rs:48:5
stack backtrace:
   0:        0x1060eeff1 - std::backtrace_rs::backtrace::libunwind::trace::h1dc1870269c8628b
                               at /rustc/41dfaaa3c66759395835b3af59b22f4f22175dc8/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x1060eeff1 - std::backtrace_rs::backtrace::trace_unsynchronized::ha7ef99260fae753b
                               at /rustc/41dfaaa3c66759395835b3af59b22f4f22175dc8/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x1060eeff1 - std::sys_common::backtrace::_print_fmt::hba0b537531255daa
                               at /rustc/41dfaaa3c66759395835b3af59b22f4f22175dc8/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x1060eeff1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hec762383110a7685
                               at /rustc/41dfaaa3c66759395835b3af59b22f4f22175dc8/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x1061047ab - core::fmt::write::h2d5ecb4b9764759c
                               at /rustc/41dfaaa3c66759395835b3af59b22f4f22175dc8/library/core/src/fmt/mod.rs:1162:17
   5:        0x1060ed52a - std::io::Write::write_fmt::h9d7d3ae333151289
                               at /rustc/41dfaaa3c66759395835b3af59b22f4f22175dc8/library/std/src/io/mod.rs:1695:15
   6:        0x1060f0745 - std::sys_common::backtrace::_print::h5df039f21c33cd5a
                               at /rustc/41dfaaa3c66759395835b3af59b22f4f22175dc8/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x1060f0745 - std::sys_common::backtrace::print::ha89aaa3259d98e13
                               at /rustc/41dfaaa3c66759395835b3af59b22f4f22175dc8/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x1060f0745 - std::panicking::default_hook::{{closure}}::h552de0233eed7dab
                               at /rustc/41dfaaa3c66759395835b3af59b22f4f22175dc8/library/std/src/panicking.rs:210:50
   9:        0x1060f032f - std::panicking::default_hook::hf4e8e1e5a5c43b90
                               at /rustc/41dfaaa3c66759395835b3af59b22f4f22175dc8/library/std/src/panicking.rs:227:9
  10:        0x1060f0e30 - std::panicking::rust_panic_with_hook::h7c7e0153f3e14d6b
                               at /rustc/41dfaaa3c66759395835b3af59b22f4f22175dc8/library/std/src/panicking.rs:624:17
  11:        0x1060f08ce - std::panicking::begin_panic_handler::{{closure}}::h3c7f7ffd2b05c635
                               at /rustc/41dfaaa3c66759395835b3af59b22f4f22175dc8/library/std/src/panicking.rs:521:13
  12:        0x1060ef467 - std::sys_common::backtrace::__rust_end_short_backtrace::h3bdf4f6c89eee6ea
                               at /rustc/41dfaaa3c66759395835b3af59b22f4f22175dc8/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x1060f083a - rust_begin_unwind
                               at /rustc/41dfaaa3c66759395835b3af59b22f4f22175dc8/library/std/src/panicking.rs:517:5
  14:        0x106111c5f - core::panicking::panic_fmt::h88a1b6fbb9084d2c
                               at /rustc/41dfaaa3c66759395835b3af59b22f4f22175dc8/library/core/src/panicking.rs:100:14
  15:        0x106103947 - core::panicking::assert_failed_inner::h755f5b129a6be052
                               at /rustc/41dfaaa3c66759395835b3af59b22f4f22175dc8/library/core/src/panicking.rs:181:17
  16:        0x10610af0e - core::panicking::assert_failed::h9c86835bf37a4d9f
  17:        0x10602a7c4 - neon_runtime::napi::error::throw::h58518d29aaf02ca2
  18:        0x106008c7d - neon::context::internal::Scope<R>::with::h72bed732c507f372
  19:        0x106019126 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hb284d668e109e7e5
  20:        0x106028537 - neon::event::event_queue::ChannelState::callback::h054a30165642d497
  21:        0x10004af13 - __ZN12_GLOBAL__N_16v8impl18ThreadSafeFunction6IdleCbEP9uv_idle_s
  22:        0x1009e9138 - _uv__run_idle
  23:        0x1009e3b84 - _uv_run
  24:        0x100041c00 - __ZN4node5StartEPN2v87IsolateEPNS_11IsolateDataERKNSt3__16vectorINS5_12basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEENSA_ISC_EEEESG_
  25:        0x100040cc2 - __ZN4node5StartEP9uv_loop_sRKNSt3__16vectorINS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS7_IS9_EEEESD_
  26:        0x100040984 - __ZN4node5StartEiPPc
fatal runtime error: failed to initiate panic, error 5
```

**Comment by kjvalencik** [comment]
This is expected behavior. It is not allowed to call any methods on context while an exception is pending. If you want to catch the exception and then throw a different error, cx.try_catch is required.

**Comment by aajit232** [comment]
Facing same error, no workarounds have worked till now

**Comment by kjvalencik** [comment]
@aajit232 do you have the same `PendingException` assertion panic? If so, this is **expected** behavior. It is not possible to call into the JavaScript VM when an exception is pending. There are one of two options:

* Short-circuit and return the `Err(Throw)` immediately. This is _typically_ what you want to do
* Catch the exception with [`cx.try_catch(..)`](https://docs.rs/neon/latest/neon/context/trait.Context.html#method.try_catch)

To catch the exception:

```rs
let _ = cx.try_catch(|cx| {
    cx.throw_error("This will be caught")?;
    Ok(())
});
```
