### ISSUE TITLE
neon build error in Windows10 + Node.js v16.13.0 + node-gyp v7.1.2

### ISSUE THREAD

**Issue by JiquanWang99** [neon-bindings/neon#822]
When I run `neon build`, the errors occur, how should I fix it?

```
error: failed to run custom build command for `neon-sys v0.9.1`

Caused by:
  process didn't exit successfully: `E:\个人项目-Rust\19.node_call_rust\native_counter\native\target\debug\build\neon-sys-4ead150af080b023\build-script-build` (exit code: 101)
  --- stdout
  'Skipping node-gyp installation as part of npm install.'

  --- stderr
  thread 'main' panicked at 'Failed to run "node-gyp configure" for neon-sys!
   Out:
  > configure-debug
  > node-gyp configure --verbose --debug


   Err: gyp info it worked if it ends with ok
  gyp verb cli [
  gyp verb cli   'D:\\nodejs\\node.exe',
  gyp verb cli   'E:\\个人项目-Rust\\19.node_call_rust\\native_counter\\native\\target\\x86_64-pc-windows-msvc\\debug\\build\\neon-sys-e437c61b0b46c160\\out\\native\\node_modules\\node-gyp\\bin\\node-gyp.js',
  gyp verb cli   'configure',
  gyp verb cli   '--verbose',
  gyp verb cli   '--debug'
  gyp verb cli ]
  gyp info using node-gyp@7.1.2
  gyp info using node@16.13.0 | win32 | x64
  gyp verb command configure []
  gyp verb find Python checking Python explicitly set from command line or npm configuration
  gyp verb find Python - "--python=" or "npm config get python" is "D:\Python27\python.exe"
  gyp verb find Python - executing "D:\Python27\python.exe" to get executable path
  gyp verb find Python - executable path is "D:\Python27\python.exe"
  gyp verb find Python - executing "D:\Python27\python.exe" to get version
  gyp verb find Python - version is "2.7.18"
  gyp info find Python using Python version 2.7.18 found at "D:\Python27\python.exe"
  gyp verb get node dir no --target version specified, falling back to host node version: 16.13.0
  gyp verb command install [ '16.13.0' ]
  gyp verb install input version string "16.13.0"
  gyp verb install installing version: 16.13.0
  gyp verb install --ensure was passed, so won't reinstall if already installed
  gyp verb install version is already installed, need to check "installVersion"
  gyp verb got "installVersion" 9
  gyp verb needs "installVersion" 9
  gyp verb install version is good
  gyp verb get node dir target node version installed: 16.13.0
  gyp verb build dir attempting to create "build" dir: E:\个人项目-Rust\19.node_call_rust\native_counter\native\target\x86_64-pc-windows-msvc\debug\build\neon-sys-e437c61b0b46c160\out\native\build
  gyp verb build dir "build" dir needed to be created? E:\个人项目-Rust\19.node_call_rust\native_counter\native\target\x86_64-pc-windows-msvc\debug\build\neon-sys-e437c61b0b46c160\out\native\build
  gyp verb find VS msvs_version was set from command line or npm config
  gyp verb find VS - looking for Visual Studio version 2017
  gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
  gyp verb find VS checking VS2019 (16.11.31624.102) found at:
  gyp verb find VS "D:\Visual Studio IDE"
  gyp verb find VS - found "Visual Studio C++ core features"
  gyp verb find VS - found VC++ toolset: v142
  gyp verb find VS - missing any Windows SDK
  gyp verb find VS checking VS2017 (15.9.28307.1705) found at:
  gyp verb find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
  gyp verb find VS - found "Visual Studio C++ core features"
  gyp verb find VS - found VC++ toolset: v141
  gyp verb find VS - found Windows SDK: 10.0.17763.0
  gyp info find VS using VS2017 (15.9.28307.1705) found at:
  gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
  gyp info find VS run with --verbose for detailed information
  gyp verb build/config.gypi creating config file
  gyp verb build/config.gypi writing out config file: E:\个人项目-Rust\19.node_call_rust\native_counter\native\target\x86_64-pc-windows-msvc\debug\build\neon-sys-e437c61b0b46c160\out\native\build\config.gypi
  (node:21992) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
  (Use `node --trace-deprecation ...` to show where the warning was created)
  gyp verb config.gypi checking for gypi file: E:\个人项目-Rust\19.node_call_rust\native_counter\native\target\x86_64-pc-windows-msvc\debug\build\neon-sys-e437c61b0b46c160\out\native\config.gypi
  gyp verb common.gypi checking for gypi file: E:\个人项目-Rust\19.node_call_rust\native_counter\native\target\x86_64-pc-windows-msvc\debug\build\neon-sys-e437c61b0b46c160\out\native\common.gypi
  gyp verb gyp gyp format was not specified; forcing "msvs"
  gyp info spawn D:\Python27\python.exe
  gyp info spawn args [
  gyp info spawn args   'E:\\个人项目-Rust\\19.node_call_rust\\native_counter\\native\\target\\x86_64-pc-windows-msvc\\debug\\build\\neon-sys-e437c61b0b46c160\\out\\native\\node_modules\\node-gyp\\gyp\\gyp_main.py',
  gyp info spawn args   'binding.gyp',
  gyp info spawn args   '-f',
  gyp info spawn args   'msvs',
  gyp info spawn args   '-I',
  gyp info spawn args   'E:\\个人项目-Rust\\19.node_call_rust\\native_counter\\native\\target\\x86_64-pc-windows-msvc\\debug\\build\\neon-sys-e437c61b0b46c160\\out\\native\\build\\config.gypi',
  gyp info spawn args   '-I',
  gyp info spawn args   'E:\\个人项目-Rust\\19.node_call_rust\\native_counter\\native\\target\\x86_64-pc-windows-msvc\\debug\\build\\neon-sys-e437c61b0b46c160\\out\\native\\node_modules\\node-gyp\\addon.gypi',
  gyp info spawn args   '-I',
  gyp info spawn args   'C:\\Users\\JqWang\\AppData\\Local\\node-gyp\\Cache\\16.13.0\\include\\node\\common.gypi',
  gyp info spawn args   '-Dlibrary=shared_library',
  gyp info spawn args   '-Dvisibility=default',
  gyp info spawn args   '-Dnode_root_dir=C:\\Users\\JqWang\\AppData\\Local\\node-gyp\\Cache\\16.13.0',
  gyp info spawn args   '-Dnode_gyp_dir=E:\\个人项目-Rust\\19.node_call_rust\\native_counter\\native\\target\\x86_64-pc-windows-msvc\\debug\\build\\neon-sys-e437c61b0b46c160\\out\\native\\node_modules\\node-gyp',
  gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\JqWang\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.13.0\\\\<(target_arch)\\\\node.lib',
  gyp info spawn args   '-Dmodule_root_dir=E:\\个人项目-Rust\\19.node_call_rust\\native_counter\\native\\target\\x86_64-pc-windows-msvc\\debug\\build\\neon-sys-e437c61b0b46c160\\out\\native',
  gyp info spawn args   '-Dnode_engine=v8',
  gyp info spawn args   '--depth=.',
  gyp info spawn args   '--no-parallel',
  gyp info spawn args   '--generator-output',
  gyp info spawn args   'E:\\个人项目-Rust\\19.node_call_rust\\native_counter\\native\\target\\x86_64-pc-windows-msvc\\debug\\build\\neon-sys-e437c61b0b46c160\\out\\native\\build',
  gyp info spawn args   '-Goutput_dir=.'
  gyp info spawn args ]
  Traceback (most recent call last):
    File "E:\������Ŀ-Rust\19.node_call_rust\native_counter\native\target\x86_64-pc-windows-msvc\debug\build\neon-sys-e437c61b0b46c160\out\native\node_modules\node-gyp\gyp\gyp_main.py", line 51, in <module>
      sys.exit(gyp.script_main())
    File "E:\������Ŀ-Rust\19.node_call_rust\native_counter\native\target\x86_64-pc-windows-msvc\debug\build\neon-sys-e437c61b0b46c160\out\native\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 670, in script_main
      return main(sys.argv[1:])
    File "E:\������Ŀ-Rust\19.node_call_rust\native_counter\native\target\x86_64-pc-windows-msvc\debug\build\neon-sys-e437c61b0b46c160\out\native\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 662, in main
      return gyp_main(args)
    File "E:\������Ŀ-Rust\19.node_call_rust\native_counter\native\target\x86_64-pc-windows-msvc\debug\build\neon-sys-e437c61b0b46c160\out\native\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 647, in gyp_main
      generator.GenerateOutput(flat_list, targets, data, params)
    File "E:\������Ŀ-Rust\19.node_call_rust\native_counter\native\target\x86_64-pc-windows-msvc\debug\build\neon-sys-e437c61b0b46c160\out\native\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2132, in GenerateOutput
      target_list, target_dicts, options, msvs_version
    File "E:\������Ŀ-Rust\19.node_call_rust\native_counter\native\target\x86_64-pc-windows-msvc\debug\build\neon-sys-e437c61b0b46c160\out\native\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1936, in _CreateProjectObjects
      guid = _GetGuidOfProject(proj_path, spec)
    File "E:\������Ŀ-Rust\19.node_call_rust\native_counter\native\target\x86_64-pc-windows-msvc\debug\build\neon-sys-e437c61b0b46c160\out\native\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 985, in _GetGuidOfProject
      guid = guid or MSVSNew.MakeGuid(proj_path)
    File "E:\������Ŀ-Rust\19.node_call_rust\native_counter\native\target\x86_64-pc-windows-msvc\debug\build\neon-sys-e437c61b0b46c160\out\native\node_modules\node-gyp\gyp\pylib\gyp\MSVSNew.py", line 51, in MakeGuid
      d = hashlib.md5((str(seed) + str(name)).encode("utf-8")).hexdigest().upper()
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xb8 in position 11: ordinal not in range(128)
  gyp ERR! configure error
  gyp ERR! stack Error: `gyp` failed with exit code: 1
  gyp ERR! stack     at ChildProcess.onCpExit (E:\个人项目-Rust\19.node_call_rust\native_counter\native\target\x86_64-pc-windows-msvc\debug\build\neon-sys-e437c61b0b46c160\out\native\node_modules\node-gyp\lib\configure.js:351:16)
  gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
  gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
  gyp ERR! System Windows_NT 10.0.19042
  gyp ERR! command "D:\\nodejs\\node.exe" "E:\\个人项目-Rust\\19.node_call_rust\\native_counter\\native\\target\\x86_64-pc-windows-msvc\\debug\\build\\neon-sys-e437c61b0b46c160\\out\\native\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--verbose" "--debug"
  gyp ERR! cwd E:\个人项目-Rust\19.node_call_rust\native_counter\native\target\x86_64-pc-windows-msvc\debug\build\neon-sys-e437c61b0b46c160\out\native
  gyp ERR! node -v v16.13.0
  gyp ERR! node-gyp -v v7.1.2
  gyp ERR! not ok
  ', C:\Users\JqWang\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\neon-sys-0.9.1\build.rs:176:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (C:\Users\JqWang\AppData\Roaming\npm\node_modules\neon-cli\lib\target.js:98:27)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\JqWang\AppData\Roaming\npm\node_modules\neon-cli\lib\target.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by kjvalencik** [comment]
Neon will accept a patch to resolve this, but the legacy backend is no longer being developed. `npm init neon [my-project]` will initialize a project with the Node-API backend.
