### ISSUE TITLE
failed to run custom build command for `neon-sys v0.3.3

### ISSUE THREAD

**Issue by jingxiawl** [neon-bindings/neon#844]
```javascript
> electron-build-env neon build p-clipboard --release

neon info forcing rebuild for new build settings
neon info running cargo
   Compiling semver-parser v0.7.0
   Compiling cfg-if v0.1.10
   Compiling cslice v0.2.0
   Compiling winapi v0.3.8
   Compiling neon-sys v0.3.3
   Compiling semver v0.9.0
   Compiling clipboard-win v2.2.0
error: failed to run custom build command for `neon-sys v0.3.3`

Caused by:
  process didn't exit successfully: `D:\webDevelep\HTML5project\BigDataFinTech\HTML5\gxwork\node_modules\p-clipboard\native\target\release\build\neon-sys-169a77d9742248b5\build-script-build` (exit code: 101)
  --- stdout
  'Skipping node-gyp installation as part of npm install.'
  up to date in 1.803s

  --- stderr
  thread 'main' panicked at 'Failed to run "node-gyp configure" for neon-sys!
   Out:
  > @ configure-release D:\webDevelep\HTML5project\BigDataFinTech\HTML5\gxwork\node_modules\p-clipboard\native\target\release\build\neon-sys-1fd61e2455ba298e\out\native
  > node-gyp configure --verbose


  D:\webDevelep\HTML5project\BigDataFinTech\HTML5\gxwork\node_modules\p-clipboard\native\target\release\build\neon-sys-1fd61e2455ba298e\out\native>if not defined npm_config_node_gyp 
(node "D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --verbose )  else (node "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure --verbose )

   Err: gyp info it worked if it ends with ok
  gyp verb cli [
  gyp verb cli   'D:\\Program Files\\nodejs\\node.exe',
  gyp verb cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
  gyp verb cli   'configure',
  gyp verb cli   '--verbose'
  gyp verb cli ]
  gyp info using node-gyp@5.1.0
  gyp info using node@14.18.0 | win32 | x64
  gyp verb command configure []
  gyp verb download using dist-url https://atom.io/download/electron
  gyp verb find Python Python is not set from command line or npm configuration
  gyp verb find Python Python is not set from environment variable PYTHON
  gyp verb find Python checking if "python" can be used
  gyp verb find Python - executing "python" to get executable path
  gyp verb find Python - "python" is not in PATH or produced an error
  gyp verb find Python checking if "python2" can be used
  gyp verb find Python - executing "python2" to get executable path
  gyp verb find Python - "python2" is not in PATH or produced an error
  gyp verb find Python checking if "python3" can be used
  gyp verb find Python - executing "python3" to get executable path
  gyp verb find Python - "python3" is not in PATH or produced an error
  gyp verb find Python checking if the py launcher can be used to find Python 2
  gyp verb find Python - executing "py.exe" to get Python 2 executable path
  gyp verb find Python - "py.exe" is not in PATH or produced an error
  gyp verb find Python checking if Python is C:\Python27\python.exe
  gyp verb find Python - executing "C:\Python27\python.exe" to get version
  gyp verb find Python - "C:\Python27\python.exe" could not be run
  gyp verb find Python checking if Python is C:\Python37\python.exe
  gyp verb find Python - executing "C:\Python37\python.exe" to get version
  gyp verb find Python - "C:\Python37\python.exe" could not be run
  gyp ERR! find Python
  gyp ERR! find Python Python is not set from command line or npm configuration
  gyp ERR! find Python Python is not set from environment variable PYTHON
  gyp ERR! find Python checking if "python" can be used
  gyp ERR! find Python - "python" is not in PATH or produced an error
  gyp ERR! find Python checking if "python2" can be used
  gyp ERR! find Python - "python2" is not in PATH or produced an error
  gyp ERR! find Python checking if "python3" can be used
  gyp ERR! find Python - "python3" is not in PATH or produced an error
  gyp ERR! find Python checking if the py launcher can be used to find Python 2
  gyp ERR! find Python - "py.exe" is not in PATH or produced an error
  gyp ERR! find Python checking if Python is C:\Python27\python.exe
  gyp ERR! find Python - "C:\Python27\python.exe" could not be run
  gyp ERR! find Python checking if Python is C:\Python37\python.exe
  gyp ERR! find Python - "C:\Python37\python.exe" could not be run
  gyp ERR! find Python
  gyp ERR! find Python **********************************************************
  gyp ERR! find Python You need to install the latest version of Python.
  gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
  gyp ERR! find Python you can try one of the following options:
  gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
  gyp ERR! find Python   (accepted by both node-gyp and npm)
  gyp ERR! find Python - Set the environment variable PYTHON
  gyp ERR! find Python - Set the npm configuration variable python:
  gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
  gyp ERR! find Python For more information consult the documentation at:
  gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
  gyp ERR! find Python **********************************************************
  gyp ERR! find Python
  gyp ERR! configure error
  gyp ERR! stack Error: Could not find any Python installation to use
  gyp ERR! stack     at PythonFinder.fail (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
  gyp ERR! stack     at PythonFinder.runChecks (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
  gyp ERR! stack     at PythonFinder.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
  gyp ERR! stack     at PythonFinder.execFileCallback (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
  gyp ERR! stack     at exithandler (child_process.js:390:5)
  gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:402:5)
  gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
  gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
  gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
  gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
  gyp ERR! System Windows_NT 10.0.19042
  gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--verbose"
  gyp ERR! cwd D:\webDevelep\HTML5project\BigDataFinTech\HTML5\gxwork\node_modules\p-clipboard\native\target\release\build\neon-sys-1fd61e2455ba298e\out\native
  gyp ERR! node -v v14.18.0
  gyp ERR! node-gyp -v v5.1.0
  gyp ERR! not ok
  npm ERR! code ELIFECYCLE
  npm ERR! errno 1
  npm ERR! @ configure-release: `node-gyp configure --verbose`
  npm ERR! Exit status 1
  npm ERR!
  npm ERR! Failed at the @ configure-release script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

  npm ERR! A complete log of this run can be found in:
  npm ERR!     C:\Users\25085\AppData\Roaming\npm-cache\_logs\2022-01-18T12_55_04_807Z-debug.log
  ', C:\Users\25085\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\neon-sys-0.3.3\build.rs:148:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (D:\webDevelep\HTML5project\BigDataFinTech\HTML5\gxwork\node_modules\neon-cli\lib\target.js:98:27)
    at Generator.next (<anonymous>)
    at fulfilled (D:\webDevelep\HTML5project\BigDataFinTech\HTML5\gxwork\node_modules\neon-cli\lib\target.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
electron-build-env error
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! GXWork@1.1.0 postbuild: `electron-build-env neon build p-clipboard --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the GXWork@1.1.0 postbuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\25085\AppData\Roaming\npm-cache\_logs\2022-01-18T12_55_06_040Z-debug.log
error Command failed with exit code 1.
```

i can not find how to fix this ,help!!

**Comment by kjvalencik** [comment]
@jingxiawl Reading the log, it looks like Python is not installed. This is a dependency of `node-gyp` and therefore a transitive dependency of Neon with the legacy backend.

Take a look at these recommendations for required tools to build native extensions:
https://github.com/nodejs/node-gyp#on-windows
