### ISSUE TITLE
Error when running npm install after creating a sample project using `neon new`

### ISSUE THREAD

**Issue by opensourcegeek** [neon-bindings/neon#94]
I get the following error, when I run `npm install` - I've added RUST_BACKTRACE=1, you can see the output below.

It's a Fedora 22 64-bit box, please let me know if you require any more details.

```
> neon-hello@0.1.0 install /home/opensourcegeek/projects/neon-hello
> neon build

neon info running cargo
neon info cargo build --release
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading neon v0.1.10
 Downloading neon-sys v0.1.10
 Downloading cslice v0.1.1
   Compiling cslice v0.1.1
   Compiling gcc v0.3.28
   Compiling neon-sys v0.1.10
failed to run custom build command for `neon-sys v0.1.10`
Process didn't exit successfully: `/home/opensourcegeek/projects/neon-hello/native/target/release/build/neon-sys-1a1cc9f341d21976/build-script-build` (exit code: 101)
--- stdout

> @ install /home/opensourcegeek/.cargo/registry/src/github.com-88ac128001ac3a9a/neon-sys-0.1.10
> node-gyp rebuild

make: Entering directory '/home/opensourcegeek/.cargo/registry/src/github.com-88ac128001ac3a9a/neon-sys-0.1.10/build'
  CXX(target) Debug/obj.target/neon/src/neon.o
  SOLINK_MODULE(target) Debug/obj.target/neon.node
  COPY Debug/neon.node
make: Leaving directory '/home/opensourcegeek/.cargo/registry/src/github.com-88ac128001ac3a9a/neon-sys-0.1.10/build'

> @ configure-release /home/opensourcegeek/.cargo/registry/src/github.com-88ac128001ac3a9a/neon-sys-0.1.10
> node-gyp configure


> @ build-release /home/opensourcegeek/.cargo/registry/src/github.com-88ac128001ac3a9a/neon-sys-0.1.10
> node-gyp build

make: Entering directory '/home/opensourcegeek/.cargo/registry/src/github.com-88ac128001ac3a9a/neon-sys-0.1.10/build'
make: Nothing to be done for 'all'.
make: Leaving directory '/home/opensourcegeek/.cargo/registry/src/github.com-88ac128001ac3a9a/neon-sys-0.1.10/build'
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
AR_x86_64-unknown-linux-gnu = None
AR_x86_64_unknown_linux_gnu = None
HOST_AR = None
AR = None
TARGET = Some("x86_64-unknown-linux-gnu")
running: "ar" "crus" "/home/opensourcegeek/projects/neon-hello/native/target/release/build/neon-sys-1a1cc9f341d21976/out/libneon.a" "build/Release/obj.target/neon/src/neon.o"
ExitStatus(ExitStatus(256))


command did not execute successfully, got: exit code: 1



--- stderr
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
npm WARN package.json @ No license field.
In file included from ../src/neon.cc:7:0:
../src/neon_string.h: In member function ‘v8::Local<v8::String> neon::Slice::ToJsString(v8::Isolate*, const char*)’:
../src/neon_string.h:28:27: warning: ignoring return value of ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const [with S = v8::String; T = v8::String]’, declared with attribute warn_unused_result [-Wunused-result]
     maybe.ToLocal(&result);
                           ^
ar: `u' modifier ignored since `D' is the default (see `U')
ar: build/Release/obj.target/neon/src/neon.o: No such file or directory
thread '<main>' panicked at 'explicit panic', /home/opensourcegeek/.cargo/registry/src/github.com-88ac128001ac3a9a/gcc-0.3.28/src/lib.rs:840
stack backtrace:
   1:     0x55be5fdc56a0 - sys::backtrace::tracing::imp::write::h3675b4f0ca767761Xcv
   2:     0x55be5fdcc4db - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44519
   3:     0x55be5fdcc148 - panicking::default_handler::h18faf4fbd296d909lSz
   4:     0x55be5fdb658c - sys_common::unwind::begin_unwind_inner::hfb5d07d6e405c6bbg1t
   5:     0x55be5fdadaef - sys_common::unwind::begin_unwind::h18372930996842594775
   6:     0x55be5fdb3f65 - fail::h4ca9f083e131b5bcC5a
   7:     0x55be5fdb3b48 - run::hbd168e69c3d4cbfeY1a
   8:     0x55be5fdabebf - Config::compile::ha31f8f7e129bbc993ja
   9:     0x55be5fda7da6 - link_library::h13cb61ee50cc4affsca
                        at /home/opensourcegeek/.cargo/registry/src/github.com-88ac128001ac3a9a/neon-sys-0.1.10/build.rs:35
  10:     0x55be5fdaa4bd - main::hf96f64c18fe799dfEca
                        at /home/opensourcegeek/.cargo/registry/src/github.com-88ac128001ac3a9a/neon-sys-0.1.10/build.rs:45
  11:     0x55be5fdcbda4 - sys_common::unwind::try::try_fn::h14622312129452522850
  12:     0x55be5fdc4a9b - __rust_try
  13:     0x55be5fdcb83b - rt::lang_start::h0ba42f7a8c46a626rKz
  14:     0x55be5fdaa4f9 - main
  15:     0x7fa56ac406ff - __libc_start_main
  16:     0x55be5fda3988 - _start
  17:                0x0 - <unknown>

neon ERR! cargo build failed

npm ERR! Linux 4.3.4-200.fc22.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! neon-hello@0.1.0 install: `neon build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the neon-hello@0.1.0 install script 'neon build'.
npm ERR! This is most likely a problem with the neon-hello package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     neon build
npm ERR! You can get their info via:
npm ERR!     npm owner ls neon-hello
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/opensourcegeek/projects/neon-hello/npm-debug.log

```

**Comment by opensourcegeek** [comment]
I've updated rustc version so I thought I'll give neon a go again but I'm still running into issue as below, any ideas?

```
projects]# neon new neon-sample
This utility will walk you through creating the neon-sample Neon project.
It only covers the most common items, and tries to guess sensible defaults.

Press ^C at any time to quit.
? version 0.1.0
? description 
? node entry point lib/index.js
? git repository 
? author 
? email 
? license MIT

Woo-hoo! Your Neon project has been created in: neon-sample

The main Node entry point is at: neon-sample/lib/index.js
The main Rust entry point is at: neon-sample/native/src/lib.rs

To build your project, just run npm install from within the neon-sample directory.
Then you can test it out with node -e 'require("./")'.

Happy hacking!

neon-sample]# npm install
npm WARN package.json neon-sample@0.1.0 No description
npm WARN package.json neon-sample@0.1.0 No repository field.
npm WARN cannot run in wd neon-sample@0.1.0 neon build (wd=/home/opensourcegeek/projects/neon-sample)
neon-cli@0.1.7 node_modules/neon-cli
├── semver@5.3.0
├── shallow-copy@0.0.1
├── in-publish@2.0.0
├── minimist@1.2.0
├── toml@2.3.0
├── git-config@0.0.7 (iniparser@1.0.5)
├── validate-npm-package-name@2.2.2 (builtins@0.0.7)
├── rsvp@3.2.1
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, strip-ansi@3.0.1, has-ansi@2.0.0)
├── validate-npm-package-license@3.0.1 (spdx-correct@1.0.2, spdx-expression-parse@1.0.2)
├── fs-extra@0.26.7 (path-is-absolute@1.0.0, klaw@1.3.0, graceful-fs@4.1.5, jsonfile@2.3.1, rimraf@2.5.4)
├── inquirer@0.11.4 (strip-ansi@3.0.1, ansi-regex@2.0.0, ansi-escapes@1.4.0, rx-lite@3.1.2, through@2.3.8, cli-width@1.1.1, figures@1.7.0, readline2@1.0.1, string-width@1.0.2, cli-cursor@1.0.2, run-async@0.1.0, lodash@3.10.1)
└── handlebars@4.0.5 (async@1.5.2, source-map@0.4.4, optimist@0.6.1, uglify-js@2.7.2)

neon-sample]# node -e 'require("./")'
module.js:340
    throw err;
    ^

Error: Cannot find module '../native'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/opensourcegeek/projects/neon-sample/lib/index.js:1:75)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)

```

**Comment by opensourcegeek** [comment]
Any ideas please?

**Comment by kjvalencik** [comment]
@opensourcegeek, it appears that you are running as root. The key log line:

```
npm WARN cannot run in wd neon-sample@0.1.0 neon build (wd=/home/opensourcegeek/projects/neon-sample
```

`npm` attempts to step down from root as a security measure, but then it doesn't have access to write to that directory. I recommend not running as root and changing the permissions on the directory. If you must run as root you can do `npm install --unsafe-perm`.

**Comment by opensourcegeek** [comment]
Thanks - I just checked and I cannot figure out what is running as root. The only thing I installed as root is `npm install -g neon`. After that project was created as normal user and I ran `npm install` as normal user as well. 

Could you please tell me if it's OK to install neon globally as root user and then use it as normal user after that?

**Comment by awkure** [comment]
Still having this issue on Fedora 27

**Comment by kjvalencik** [comment]
Closing since this was likely a permissions issue and pertains to the legacy backend which is no longer default and will be removed in a future version.
